# Preprocessing of the RTS data to prepare for the Issue Index creation

In [2]:
import os
import json
from bs4 import BeautifulSoup
from datetime import datetime
import pandas as pd
from tqdm import tqdm
import csv

### Directory Structure: `/mnt/project_impresso/original/RTS`

The RTS directory contains radio content organized by program/show names. The filesystem structure is organized as follows:

```
/mnt/project_impresso/original/RTS/
│
├── News Programs (Journaux)
│   ├── j_mat/                    (morning news)  
│   │   ├── audio                       (all PM3 audio files)
│   │   ├── stt                         (all stt and xml files containing the text related to each audio file)
│   │   ├── ExpXml-20251106-122951.xml  (xml files with the metadata relating the MP3 audio and XML files for each listing)
│   │   ...  
│   │   └── ExpXml-20251113-171933.xml                   
│   ├── j_midi/                   (midday news)
│   ├── j13h/                     (1 PM news)
│   ├── j13h2/                    (1 PM news variant)
│   ├── j_soir/                   (evening news)
│   └── j_nuit/                   (night news)
│
...
│
└── Other Programs
    ├── petitdej/                 (breakfast)
    ├── ana_media/                (media analysis)
    ├── geneve_info/              (Geneva information)
    └── enquest/                  (enquête/investigation)
```

Each directory contains media files (audio recordings and associated metadata) for that specific radio program.

In [3]:
base_dir = "/mnt/project_impresso/original/RTS"

audios_subdir = 'audio'
asr_subdir = 'stt'
metadata_file_start = "ExpXml"

## Process an example of metadata xml file to extract the contents

In [4]:
example_program = "causerie_uni"

example_program_dir = os.path.join(base_dir, example_program)

ex_meta_files = [os.path.join(example_program_dir,f) for f in os.listdir(example_program_dir) if f.startswith(metadata_file_start)]
ex_meta_files

['/mnt/project_impresso/original/RTS/causerie_uni/ExpXml-20251029-131700.xml',
 '/mnt/project_impresso/original/RTS/causerie_uni/ExpXml-20251029-132007.xml']

In [25]:
with open(ex_meta_files[0], "r", encoding="utf-8") as f:
    raw_xml = f.read()

xml_doc = BeautifulSoup(raw_xml, "xml")
xml_doc

<?xml version="1.0" encoding="utf-8"?>
<DOCUMENTS><DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}</OID><LOGIN/><TITLE>Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg</TITLE><HIERARCHY OID="{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}" current="*" depth="---" title="Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg"/><SEQUENCE>1</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Pologne</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>albrecjo</MODIFIEDBY><MODIFIEDON>25.05.2022 03:56:53</MODIFIEDON><HISTORY>Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Cros, Edouard</NAME><FUNCTION>Conf?rencier/e</FUNCTION><RO

In [6]:
docs = xml_doc.find_all("DOCUMENT")
docs 

[<DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}</OID><LOGIN/><TITLE>Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg</TITLE><HIERARCHY OID="{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}" current="*" depth="---" title="Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg"/><SEQUENCE>1</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Pologne</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>albrecjo</MODIFIEDBY><MODIFIEDON>25.05.2022 03:56:53</MODIFIEDON><HISTORY>Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Cros, Edouard</NAME><FUNCTION>Conf?rencier/e</FUNCTION><ROLE>privat-docent ? l'Universit? de Fribourg</ROLE

In [7]:
for child in docs[0].find_all(recursive=False):
    print(f"name: {child.name}")
    print(f"attrs: {child.attrs}")
    print(f"text: {child.get_text(strip=True)}")

name: CLSID
attrs: {}
text: {D2593F4E-C887-4E48-8982-5BD08BA4DAE0}
name: OID
attrs: {}
text: {3267F04D-657F-4DCB-BCB0-44B2B6C2682D}
name: LOGIN
attrs: {}
text: 
name: TITLE
attrs: {}
text: Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg
name: HIERARCHY
attrs: {'title': "Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg", 'OID': '{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}', 'depth': '---', 'current': '*'}
text: 
name: SEQUENCE
attrs: {}
text: 1
name: BROADCAST
attrs: {}
text: Causerie universitaire
name: DOCUMENTTYPE
attrs: {}
text: Parl?
name: GEOGRAPHICALDESCRIPTORS
attrs: {}
text: Pologne
name: HIERARCHYLEVEL
attrs: {}
text: Sujet
name: MODIFIEDBY
attrs: {}
text: albrecjo
name: MODIFIEDON
attrs: {}
text: 25.05.2022 03:56:53
name: HISTORY
attrs: {}
text: Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B
name: PARTICIPANTS
attrs: {}
text: Cros, 

In [12]:
# define more intuitive names
simple_fields_renaming = {
    "CLSID": "cls_ID",
    "OID": "OID",
    "LOGIN": "login",
    "TITLE": "broadcast_episode_title",
    "SEQUENCE": "sequence", 
    "BROADCAST": "broadcast_program_name",
    "DOCUMENTTYPE": "document_type",
    "HIERARCHYLEVEL": "hierarchy_level",
    "MODIFIEDBY": "modified_by",
    "MODIFIEDON": "modified_on",
    "HISTORY": "physical_support_history",
    "PRODUCTIONTYPE": "production_type",
    "RECORDINGPLACE": "recording_place",
    "RIGHTSNOTES": "rights_notes",
    "RIGHTSSTATUS": "rights_status",
    "SERIESTITLE": "series_title",
    "SUMMARY": "content_summary",
    "WORKFLOWSTATUS": "workflow_status",
    "ASSEMBLYSTATUS": "assembly_status",
    "LIVE": "live",
    "MODULATIONTYPE": "modulation_type",
    "WORKDURATION": "work_duration",
    "WORKDURATIONCOMPL": "work_duration_compl",
}

list_fields_renaming = {
    'GEOGRAPHICALDESCRIPTORS': 'geographical_descriptors',
    'PERSONDESCRIPTORS': 'person_descriptors',
    'THEMATICALDESCRIPTORS': 'thematical_descriptors',
    'RIGHTSUSAGEPOSSIBILITIES': 'rights_usage_possibilities',
    'PROGRAMMES': 'radio_channels',
    'SUBDOMAINS': 'subdomains',
    'RECORDINGDATES': 'recording_dates',
    'FIRSTBROADCASTDATES': 'first_broadcast_dates'
}

support_keys = ['spt_clsid', 'spt_oid',
                'spt_title',
                'spt_isdigital',
                'spt_filename',
                'spt_cataloguing_status',
                'spt_source',
                'spt_unit_duration']

doc_keys = ["alias", "date_str", "stt_filename", "mp3_filenames", "stripped_OID", "exact_date", "broadcast_date"] + list(simple_fields_renaming.values()) + list(list_fields_renaming.values()) + ["supports", "spt_filenames", "participants"]

In [13]:
# Parse DOCUMENT elements into structured dictionaries
def parse_docs_in_xml(xml_doc, program, all_alias_stt, all_alias_audios, doc_keys=doc_keys, simple_fields_map=simple_fields_renaming, list_fields_map=list_fields_renaming):
    """
    Extract all DOCUMENT elements from XML into a list of dictionaries.
    Handles nested structures: PARTICIPANTS, GEOGRAPHICALDESCRIPTORS, 
    THEMATICALDESCRIPTORS, SUPPORTS, RECORDINGDATES, etc.
    """
    documents = []
    
    # Find all DOCUMENT elements
    doc_elements = xml_doc.find_all('DOCUMENT')
    skipped = 0
    
    print(f"\nStarting extracting {len(doc_elements)} documents for program {program}")
    for doc_idx, doc_elem in enumerate(doc_elements):
        doc_dict = {
            "alias": program,
            "date_str": None,
            "stt_filename": None,
            "mp3_filenames": None
        }
        
        # Extract simple text fields
        
        
        for og_field, renamed_field in simple_fields_map.items():
            elem = doc_elem.find(og_field)
            if elem:
                text = elem.get_text(strip=True)
                doc_dict[renamed_field] = text
                if og_field=='OID':
                    # the text is actually "{oid}", remove start and end brackets
                    doc_dict['stripped_OID'] = text[1:-1] if text else None
            else:
                doc_dict[renamed_field] = None
        
        if "stripped_OID" not in doc_dict or not doc_dict['stripped_OID']:
            print(f"Skipping document {doc_idx+1}/{len(doc_elements)} because it's missing an OID!!")
            skipped +=1
            continue


        stt_file = f"{doc_dict['stripped_OID']}_STT.xml"
        if stt_file not in all_alias_stt:
            stt_text_file = f"{doc_dict['stripped_OID']}_STT.txt"
            print(f"Skipping document {doc_idx+1}/{len(doc_elements)} with OID {doc_dict['OID']} because it's missing its XML file!! (stt exists: {stt_text_file in all_alias_stt})")
            skipped +=1
            continue
        else:
            doc_dict['stt_filename'] = stt_file

        # Extract PARTICIPANTS (list of dicts)
        participants = []
        for participant in doc_elem.find_all('PARTICIPANT'):
            name_elem = participant.find('NAME')
            function_elem = participant.find('FUNCTION')
            role_elem = participant.find('ROLE')
            participants.append({
                'name': name_elem.get_text(strip=True) if name_elem else None,
                'function': function_elem.get_text(strip=True) if function_elem else None,
                'role': role_elem.get_text(strip=True) if role_elem else None
            })
        if participants:
            doc_dict['participants'] = participants
        
        # Extract list fields (DESCRIPTORS, PROGRAMMES, SUBDOMAINS, etc.)
        list_fields = {
            'GEOGRAPHICALDESCRIPTORS': 'GEOGRAPHICALDESCRIPTOR',
            'PERSONDESCRIPTORS': 'PERSONDESCRIPTOR',
            'THEMATICALDESCRIPTORS': 'THEMATICALDESCRIPTOR',
            'RIGHTSUSAGEPOSSIBILITIES': 'RIGHTSUSAGEPOSSIBILITY',
            'PROGRAMMES': 'PROGRAMME',
            'SUBDOMAINS': 'SUBDOMAIN',
            'RECORDINGDATES': 'RECORDINGDATE',
            'FIRSTBROADCASTDATES': 'FIRSTBROADCASTDATE'
        }
        
        for container_name, renamed_field in list_fields_map.items():
            container = doc_elem.find(container_name)
            if container:
                doc_dict[renamed_field] = [elem.get_text(strip=True) for elem in container.find_all(list_fields[container_name])]
            else:
                # always define fields, set them to None if not defined
                doc_dict[renamed_field] = None

        date_strings = None
        broadcast_date = None
        # extract the date from first_braodcast_dates
        if doc_dict["first_broadcast_dates"]:
            date_strings = [d for rd in doc_dict["first_broadcast_dates"] for d in rd.split(" - ") if d != "__/__/____"]
            broadcast_date = True 
            
        if not date_strings and doc_dict["recording_dates"]:
            print(f"Did not find any date for doc with OID {doc_dict['OID']}. Trying to use the recording date. doc_dict: {doc_dict}")
            date_strings = [d for rd in doc_dict["recording_dates"] for d in rd.split(" - ") if d != "__/__/____" and "Avant" not in d and "Apr?s" not in d]
            broadcast_date = False

        # process the dates extracted
        if not date_strings:
            print(f"WARNING! MISSING DATE FOR DOC WITH OID {doc_dict['OID']}!! \nDocument: {doc_dict}, \noriginal: {doc_elem}")
            if doc_dict['stripped_OID'] == "5D740FA1-1A90-4878-A7E2-40C43C0F6430":
                print(f"Found and setting manually the correct date for {doc_dict['OID']}: 10/04/1989")
                doc_dict['date_str'] = "10/04/1989"
                doc_dict['exact_date'] = True
                doc_dict['broadcast_date'] = True
            #doc_dict['day'] = None
        else:
            # reformat each date and keep the earliest
            dates = []
            exact_dates = []
            for s in date_strings:
                exact = True
                if "__" in s:
                    old_s = s
                    s = s.replace("__", "01")
                    exact = False
                    print(f"The date for document with OID {doc_dict['OID']} was invalid ({old_s}) - changed it to {s}")
                if s.startswith('~'):
                    final_d = datetime.strptime(s[1:],  "%d/%m/%Y")
                else:   
                    final_d = datetime.strptime(s,  "%d/%m/%Y")
                dates.append(final_d)
                if exact:
                    exact_dates.append(final_d)
                

                    
            #dates = [datetime.strptime(s[1:] if s.startswith('~') else s, "%d/%m/%Y") for s in date_strings]
            #doc_dict['year'] = min(dates).year
            #doc_dict['month'] = min(dates).month
            #doc_dict['day'] = min(dates).day
            chosen_date = min(dates)
            doc_dict['date_str'] = chosen_date.strftime('%d/%m/%Y')
            doc_dict['exact_date'] = chosen_date in exact_dates
            doc_dict['broadcast_date'] = broadcast_date
            
        
        # Extract SUPPORTS (audio files and metadata)
        supports = []
        mp3_filenames = []

        for support in doc_elem.find_all('SUPPORT'):
            support_dict = {
                'spt_clsid': support.find('CLSID').get_text(strip=True) if support.find('CLSID') else None,
                'spt_oid': support.find('OID').get_text(strip=True) if support.find('OID') else None,
                'spt_title': support.find('TITLE').get_text(strip=True) if support.find('TITLE') else None,
                'spt_isdigital': support.find('ISDIGITAL').get_text(strip=True) if support.find('ISDIGITAL') else None,
                'spt_filename': support.find('FILENAME').get_text(strip=True) if support.find('FILENAME') else None,
                'spt_cataloguing_status': support.find('CATALOGUINGSTATUS').get_text(strip=True) if support.find('CATALOGUINGSTATUS') else None,
                'spt_source': support.find('SOURCE').get_text(strip=True) if support.find('SOURCE') else None,
                'spt_unit_duration': support.find('UNITDURATION').get_text(strip=True) if support.find('UNITDURATION') else None
            }

            if support_dict['spt_filename']:
                # remove '.wav' if it's in the filename
                spt_filename = support_dict['spt_filename'].replace('.wav', "")
                # populate the list of mp3 filenames with any mp3 file which has a matching filename
                mp3_filenames.extend([audio for audio in all_alias_audios if spt_filename in audio])

            supports.append(support_dict)

        if not supports or not mp3_filenames:
            print(f"Skipping document {doc_idx+1}/{len(doc_elements)} with OID {doc_dict['OID']} because it's missing its audio MP3 file!!")
            skipped +=1
            continue

        doc_dict['supports'] = supports
        doc_dict['spt_filenames'] = [s['spt_filename'] for s in supports]
        doc_dict['mp3_filenames'] = mp3_filenames

        # before adding to the list of docs, check it has all keys, and setting any missing one to None
        for k in doc_keys:
            if k not in doc_dict:
                doc_dict[k] = None
        
        documents.append(doc_dict)

    print(f"{program} - returning {len(documents)} documents, {skipped} were skipped due to missing necessary info.")
    
    return documents

Check that the function works correctly

In [9]:

audio_files = os.listdir(os.path.join(example_program_dir, audios_subdir))
text_files = os.listdir(os.path.join(example_program_dir, asr_subdir))

# Parse all documents from the example XML
all_documents = parse_docs_in_xml(xml_doc, example_program, text_files, audio_files)

print(f"Total documents found: {len(all_documents)}")
if all_documents:
    for idx, doc in enumerate(all_documents):
        #doc = all_documents[0]
        #print(f"\nFirst document keys: {list(doc.keys())}")
        print(f"\nTitle: {doc.get('title', 'N/A')[:80]}...")
        print(f"Broadcast program name: {doc.get('broadcast_program_name', 'N/A')}")
        print(f"Extracted boradcast date: {doc['date_str']} (year {doc['date_str'].split('/')[-1]})")
        print(f"Bradcast dates: {doc.get('first_broadcast_dates', ['N/A'])[0]}, Recording dates: {doc.get('recording_dates', ['N/A'])[0]}")
        print(f"MP3 filenames: {doc.get('mp3_filenames', ['N/A'])}")
        
        if doc['mp3_filenames']:
            for f in doc.get('mp3_filenames'):
                print(f" --> MP3 filename in audios: {f in audio_files}, OID in ASR files: {any(doc['stripped_OID'] in xml_f for xml_f in text_files)}")
        else:
            print(f"Doc {idx} has no mp3 filenames!! full doc:\n{doc}")
        #if doc.get('supports'):
        #    print(f"Audio file: {doc['supports'][0].get('filename', 'N/A')}")



Starting extracting 8 documents for program causerie_uni
Skipping document 3/8 with OID {1656BB3F-A8EF-4BF4-BE9A-20483F5665C8} because it's missing its XML file!! (stt exists: False)
Skipping document 5/8 with OID {87381313-87FD-4D31-AD19-8CDC08BA94DA} because it's missing its XML file!! (stt exists: False)
causerie_uni - returning 6 documents, 2 were skipped due to missing necessary info.
Total documents found: 6

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 19/12/1939 (year 1939)
Bradcast dates: 19/12/1939 - __/__/____, Recording dates: 20/11/1939 - 20/11/1939
MP3 filenames: ['3267f04d-657f-4dcb-bcb0-44b2b6c2682d_1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 07/01/1941 (year 1941)
Bradcast dates: 07/01/1941 - __/__/____, Recording dates: 26/11/1940 - 26/11/1940


In [10]:
all_documents[:5]

[{'alias': 'causerie_uni',
  'date_str': '19/12/1939',
  'mp3_filenames': ['3267f04d-657f-4dcb-bcb0-44b2b6c2682d_1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.mp3'],
  'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}',
  'OID': '{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}',
  'stripped_OID': '3267F04D-657F-4DCB-BCB0-44B2B6C2682D',
  'login': '',
  'broadcast_episode_title': "Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg",
  'sequence': '1',
  'broadcast_program_name': 'Causerie universitaire',
  'document_type': 'Parl?',
  'hierarchy_level': 'Sujet',
  'modified_by': 'albrecjo',
  'modified_on': '25.05.2022 03:56:53',
  'physical_support_history': 'Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B',
  'production_type': 'Production propre',
  'recording_place': 'Lausanne (Studio de Radio-Lausanne)',
  'rights_notes': 'Memoriav',
  'rights_status': 'Clarifi?',
  'series_title

In [171]:
doc_keys

dict_keys(['alias', 'date_str', 'mp3_filenames', 'cls_ID', 'OID', 'stripped_OID', 'login', 'broadcast_episode_title', 'sequence', 'broadcast_program_name', 'document_type', 'hierarchy_level', 'modified_by', 'modified_on', 'physical_support_history', 'production_type', 'recording_place', 'rights_notes', 'rights_status', 'series_title', 'content_summary', 'workflow_status', 'assembly_status', 'live', 'modilation_type', 'work_duration', 'work_duration_compl', 'participants', 'geographical_descriptors', 'person_descriptors', 'thematical_descriptors', 'rights_uage_possibilities', 'radio_channels', 'subdomains', 'recording_dates', 'first_broadcast_dates', 'supports', 'spt_filenames'])

In [11]:
doc_keys = all_documents[0].keys()

out_csv_name = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/debug_metadata.csv"
with open(out_csv_name, "w", newline='') as output_file:
    dict_writer = csv.DictWriter(output_file, doc_keys)
    dict_writer.writeheader()
    dict_writer.writerows(all_documents)


This works and yields the desired set of metadata. 

## Aggregating all the programs' metadata into a single file

Now we need to write an orchestrator function that opens and processes the XML documents for each provider, and stores the info in a dict or a dataframe, also extracting the first braodcast date to help with the creation of the issue index file

In [7]:
all_program_aliases = sorted([p for p in os.listdir(base_dir) if "DS_Store" not in p and "$RECYCLE" not in p and "System" not in p])
print(f"Found {len(all_program_aliases)} Radio programs: {all_program_aliases}")

Found 47 Radio programs: ['ana_media', 'bigbang', 'canal_euro', 'causerie_uni', 'chron_instit', 'chron_unesco', 'courrier_cr', 'culte', 'dos_sci', 'ecoute_paix', 'enquest', 'forum', 'forum_lau', 'geneve_info', 'hist_ondes', 'infopile', 'inst_monde', 'j13h', 'j13h2', 'j_mat', 'j_midi', 'j_nuit', 'j_soir', 'mag_eco', 'mag_info', 'mag_sci1', 'mag_sci2', 'mag_tv1', 'mag_tv2', 'mem_ondes', 'min_oecu', 'miroir_monde', 'miroir_temps', 'monde_ant', 'monde_sem', 'nickel', 'nu_parle', 'ombres_eco', 'paraboles', 'paris_parle', 'parole_prem', 'petitdej', 'suisse_euro', 'terre_ciel', 'trib_prem', 'vie_monde', 'vie_va']


In [8]:
out_csv_name = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata.rts.csv"

In [184]:
all_program_aliases.index("mem_ondes")

29

In [29]:
already_done = all_program_aliases[:all_program_aliases.index("mem_ondes")+1]
already_done = []

In [27]:
#already_done = all_program_aliases[:all_program_aliases.index("mem_ondes")+1]
#already_done = []
already_done

[]

In [30]:
all_docs = []
all_docs_dict = {}
#doc_keys = None

for p_idx, p_alias in tqdm(enumerate(all_program_aliases)):

    if p_alias in already_done:
        print(f"\n{p_alias} is already done, skipping!")
        continue
    
    # first find all the metadata xml docs
    program_dir = os.path.join(base_dir, p_alias)
    metadata_files = [os.path.join(program_dir,f) for f in os.listdir(program_dir) if f.startswith(metadata_file_start)]
    
    all_audios_for_alias = os.listdir(os.path.join(program_dir,'audio'))
    all_stt_for_alias = os.listdir(os.path.join(program_dir,'stt'))

    print(f"\nPROCESSING PROGRAM {p_alias} ({p_idx+1}/{len(all_program_aliases)}) - {len(metadata_files)} files:")

    program_docs = []
    for xml_doc_path in tqdm(metadata_files):
        with open(xml_doc_path, "r", encoding="utf-8") as f:
            raw_xml = f.read()

        program_docs.extend(parse_docs_in_xml(BeautifulSoup(raw_xml, "xml"), p_alias, all_stt_for_alias, all_audios_for_alias, doc_keys))
    
    all_docs.extend(program_docs)
    all_docs_dict[p_alias] = program_docs

    # Save the current list of documents to save the progress
    #if not doc_keys:
    #    doc_keys = all_docs[0].keys()

    print(f" --> Adding {len(program_docs)} to the out csv for {p_alias}")
    with open(out_csv_name, "a", newline='') as output_file:
        dict_writer = csv.DictWriter(output_file, doc_keys)
        if not already_done:
            dict_writer.writeheader()
        dict_writer.writerows(program_docs)

    already_done.append(p_alias)
        


0it [00:00, ?it/s]


PROCESSING PROGRAM ana_media (1/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00, 15.58it/s]



Starting extracting 6 documents for program ana_media
ana_media - returning 6 documents, 0 were skipped due to missing necessary info.
 --> Adding 6 to the out csv for ana_media

PROCESSING PROGRAM bigbang (2/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
2it [00:00,  5.57it/s]


Starting extracting 40 documents for program bigbang
Skipping document 1/40 with OID {06660C0A-1C9C-4EEB-B9F0-9DD8977CA087} because it's missing its XML file!! (stt exists: False)
Skipping document 4/40 with OID {781626D5-C9EA-41F0-B495-42812C3C3F3F} because it's missing its XML file!! (stt exists: False)
Skipping document 6/40 with OID {42FA7346-699C-4F81-A4EF-0415C88960CD} because it's missing its XML file!! (stt exists: False)
Skipping document 9/40 with OID {D34C4835-E7BB-4C5A-9C3A-DE295A646F37} because it's missing its XML file!! (stt exists: False)
Skipping document 10/40 with OID {DB2CEE23-A884-42FD-94D5-2806D2A2553F} because it's missing its XML file!! (stt exists: False)
Skipping document 12/40 with OID {276678AF-E2C5-4E28-B471-08ABDBFF2789} because it's missing its XML file!! (stt exists: False)
Skipping document 14/40 with OID {797ED203-EDDC-4DBB-B3D9-B316EC0C9C43} because it's missing its XML file!! (stt exists: False)
Skipping document 16/40 with OID {64B8E4FD-527A-4769-9


Starting extracting 51 documents for program canal_euro


100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
3it [00:00,  5.25it/s]

WARNING! MISSING DATE FOR DOC WITH OID {5D740FA1-1A90-4878-A7E2-40C43C0F6430}!! 
Document: {'alias': 'canal_euro', 'date_str': None, 'stt_filename': '5D740FA1-1A90-4878-A7E2-40C43C0F6430_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5D740FA1-1A90-4878-A7E2-40C43C0F6430}', 'stripped_OID': '5D740FA1-1A90-4878-A7E2-40C43C0F6430', 'login': '', 'broadcast_episode_title': "Canal Europe (37/50). L'audiovisuel et le march? unique de l'Europe des Douze", 'sequence': '1', 'broadcast_program_name': 'Canal Europe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '15.07.2022 09:23:54', 'physical_support_history': "Cote d'origine : A 21376Resp. RSR : AQTLot : Caisse 2008Voir feuille d'accomp.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Participant: inte:Lhoest, Holde;  i

100%|██████████| 2/2 [00:00<00:00, 33.82it/s]



Starting extracting 8 documents for program causerie_uni
Skipping document 3/8 with OID {1656BB3F-A8EF-4BF4-BE9A-20483F5665C8} because it's missing its XML file!! (stt exists: False)
Skipping document 5/8 with OID {87381313-87FD-4D31-AD19-8CDC08BA94DA} because it's missing its XML file!! (stt exists: False)
causerie_uni - returning 6 documents, 2 were skipped due to missing necessary info.

Starting extracting 7 documents for program causerie_uni
Skipping document 7/7 with OID {D8092E5C-57F3-4BFF-98B8-F3C9380FD7E9} because it's missing its XML file!! (stt exists: False)
causerie_uni - returning 6 documents, 1 were skipped due to missing necessary info.
 --> Adding 12 to the out csv for causerie_uni

PROCESSING PROGRAM chron_instit (5/47) - 1 files:



Starting extracting 236 documents for program chron_instit
Skipping document 1/236 with OID {36993958-CC36-4058-B41C-717ACB601DED} because it's missing its XML file!! (stt exists: False)
Skipping document 2/236 with OID {C1166A0E-3B4B-4554-915E-F1C8AB56BB61} because it's missing its XML file!! (stt exists: False)
The date for document with OID {9B17EFE3-9A57-4C73-B3BE-31A0B7CD294A} was invalid (__/06/1949) - changed it to 01/06/1949
Skipping document 4/236 with OID {D187EB9A-1679-49B1-8DDF-B9CBCC830B38} because it's missing its XML file!! (stt exists: False)
Skipping document 5/236 with OID {93393999-811C-4806-8E45-9DDA258EA67A} because it's missing its XML file!! (stt exists: False)
Skipping document 6/236 with OID {826ACB35-FE97-45AD-ABA4-5E183AD09A91} because it's missing its XML file!! (stt exists: False)
Skipping document 7/236 with OID {79E28712-6F3F-41FD-8444-F259E79BF4BD} because it's missing its XML file!! (stt exists: False)
Skipping document 8/236 with OID {F796BD61-4663-43

100%|██████████| 1/1 [00:00<00:00,  1.45it/s]
5it [00:01,  3.36it/s]

The date for document with OID {C1236FA9-7285-41D0-99D2-D9326AC107BF} was invalid (~__/11/1950) - changed it to ~01/11/1950
The date for document with OID {C1236FA9-7285-41D0-99D2-D9326AC107BF} was invalid (~__/11/1950) - changed it to ~01/11/1950
Skipping document 190/236 with OID {80BD19D0-A5D9-4863-AD55-47BD49DAD22D} because it's missing its XML file!! (stt exists: False)
Skipping document 191/236 with OID {2FBD5C35-BB90-4469-A761-D003C57F9358} because it's missing its XML file!! (stt exists: False)
Skipping document 192/236 with OID {9B9076D2-8457-4A57-AD49-A3059E136ABD} because it's missing its XML file!! (stt exists: False)
Skipping document 193/236 with OID {BC74CFF9-1309-4C4B-AE58-E79A7F60F9FA} because it's missing its XML file!! (stt exists: False)
Skipping document 194/236 with OID {F92C9967-8E30-4266-95E5-C82CF53B50B2} because it's missing its XML file!! (stt exists: False)
Skipping document 195/236 with OID {B91DFD0B-03E7-4892-8917-976FC4BC80C8} because it's missing its XML

100%|██████████| 1/1 [00:00<00:00,  7.15it/s]


Starting extracting 60 documents for program chron_unesco
Skipping document 1/60 with OID {66BC1A28-5594-40B5-926B-D21D2A8E8DE5} because it's missing its XML file!! (stt exists: False)
Skipping document 2/60 with OID {0A44E2AB-2AFF-4B33-A1A4-5803861D7B20} because it's missing its XML file!! (stt exists: False)
Skipping document 3/60 with OID {F9211F57-C3A1-4734-8FAE-E3A1F4B10425} because it's missing its XML file!! (stt exists: False)
Skipping document 4/60 with OID {5345F130-FE59-4534-A05F-B3C885F3B72B} because it's missing its XML file!! (stt exists: False)
Skipping document 5/60 with OID {9D5D9EEB-7D44-4586-A218-5BC386EE1EDE} because it's missing its XML file!! (stt exists: False)
Skipping document 6/60 with OID {F06ADD23-FCC4-401A-8A79-8F6FDCA9ADC3} because it's missing its XML file!! (stt exists: False)
The date for document with OID {58F25276-A592-4AC5-A153-E66B64E3CFCF} was invalid (__/__/1952) - changed it to 01/01/1952
The date for document with OID {5703A9EC-C10A-404F-B930-5


6it [00:01,  3.90it/s]

 --> Adding 2 to the out csv for chron_unesco

PROCESSING PROGRAM courrier_cr (7/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00, 28.01it/s]



Starting extracting 15 documents for program courrier_cr
Skipping document 1/15 with OID {1073E6EE-E4F3-4964-BACE-0AB21E977484} because it's missing its XML file!! (stt exists: False)
Skipping document 2/15 with OID {65C1F992-0CB0-4915-8933-922AF48B40EC} because it's missing its XML file!! (stt exists: False)
Skipping document 3/15 with OID {7C060C62-3B86-4636-8F6A-AC0D15346922} because it's missing its XML file!! (stt exists: False)
Skipping document 4/15 with OID {6B1092F7-BD6D-4224-A2B0-1093A9DF21BD} because it's missing its XML file!! (stt exists: False)
Skipping document 5/15 with OID {7E26CAE8-DC8A-43AF-9878-DB3AA45298E5} because it's missing its XML file!! (stt exists: False)
Skipping document 6/15 with OID {AA4C5329-EBD6-4B1E-8813-4234C2B31052} because it's missing its XML file!! (stt exists: False)
Skipping document 7/15 with OID {8DBADE0E-F273-47D7-8B44-37CDB2B69DCF} because it's missing its XML file!! (stt exists: False)
Skipping document 8/15 with OID {F57F6900-1CDD-4D32-8


Starting extracting 219 documents for program culte
Skipping document 6/219 with OID {A9F197FC-FCB0-4CCA-B8D7-9BA0C07DA1FE} because it's missing its XML file!! (stt exists: False)
Skipping document 11/219 with OID {3911571A-6E64-44FB-B186-F6C86B30D933} because it's missing its XML file!! (stt exists: False)
Skipping document 20/219 with OID {88E9DCA8-3E14-4EDB-A805-CBAF972D9812} because it's missing its XML file!! (stt exists: False)
Skipping document 25/219 with OID {8CE1645D-03A3-45D9-B932-4CA900F857B8} because it's missing its XML file!! (stt exists: False)
Skipping document 26/219 with OID {5CA2BCEB-5247-4ABB-B4B5-4C796D70E4D7} because it's missing its XML file!! (stt exists: False)
Skipping document 28/219 with OID {D3BD691C-A6D0-4A27-9BB2-EC425EE78A7F} because it's missing its XML file!! (stt exists: False)
Skipping document 32/219 with OID {D2A170D1-26A6-4084-8F3F-952E082078B7} because it's missing its XML file!! (stt exists: False)
Skipping document 33/219 with OID {271B2CF1-9

100%|██████████| 1/1 [00:00<00:00,  1.17it/s]
8it [00:02,  2.86it/s]

Skipping document 117/219 with OID {517A70C9-12B2-4D55-A818-FD27C3478AF8} because it's missing its XML file!! (stt exists: False)
Skipping document 121/219 with OID {2DCAAEF0-EF29-4E92-BD82-C0EB16541740} because it's missing its XML file!! (stt exists: False)
Skipping document 129/219 with OID {39786B0B-AAAD-4367-A28D-E0B0356D395F} because it's missing its XML file!! (stt exists: False)
Skipping document 161/219 with OID {7F122966-B194-466B-83C2-5695E79033EA} because it's missing its XML file!! (stt exists: False)
Skipping document 178/219 with OID {13751DB0-9C8E-42A4-B5DC-6FCF7C961FF5} because it's missing its XML file!! (stt exists: False)
Skipping document 191/219 with OID {6D06A2C9-130B-42E6-B698-FD336F7517B0} because it's missing its XML file!! (stt exists: False)
Skipping document 208/219 with OID {356EA631-2E2B-4C00-99D7-87CAD37A8C99} because it's missing its XML file!! (stt exists: False)
Skipping document 209/219 with OID {8B5EF25B-2E1F-4B11-AD62-CEE8613C1037} because it's mis


Starting extracting 95 documents for program dos_sci
Skipping document 15/95 with OID {024E3A67-49F3-4660-861B-935F0BE9582F} because it's missing its XML file!! (stt exists: False)
Skipping document 47/95 with OID {805DD91A-5A56-482D-AFC2-1E7239C8EE31} because it's missing its XML file!! (stt exists: False)
Skipping document 51/95 with OID {6A01C6FF-93D3-4238-90EB-0A076874AC35} because it's missing its XML file!! (stt exists: False)
Skipping document 56/95 with OID {17007885-D124-4D8B-9DD9-1A89933325B1} because it's missing its XML file!! (stt exists: False)
Skipping document 58/95 with OID {BCC933E9-817D-4EB9-9379-2347524A614E} because it's missing its XML file!! (stt exists: False)
Skipping document 61/95 with OID {058CAC48-2B2B-4F32-8A15-FD87059848E1} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30}. Trying to use the recording date. doc_dict: {'alias': 'dos_sci', 'date_str': None, 'stt_filename': 

100%|██████████| 1/1 [00:00<00:00,  2.22it/s]
9it [00:02,  2.63it/s]

Skipping document 80/95 with OID {D27D4B91-5A36-4A77-A994-47D97428D356} because it's missing its XML file!! (stt exists: False)
Skipping document 81/95 with OID {173B18B3-271F-472D-B5D5-336831000CA1} because it's missing its XML file!! (stt exists: False)
Skipping document 92/95 with OID {4BB3BEBB-CC19-4C6D-9357-ED343C37C04F} because it's missing its XML file!! (stt exists: False)
dos_sci - returning 83 documents, 12 were skipped due to missing necessary info.
 --> Adding 83 to the out csv for dos_sci

PROCESSING PROGRAM ecoute_paix (10/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
10it [00:03,  2.57it/s]


Starting extracting 125 documents for program ecoute_paix
Skipping document 1/125 with OID {9590C9BC-874D-4A91-84B9-89EF0B250D68} because it's missing its XML file!! (stt exists: False)
The date for document with OID {5BF47ED2-2B35-430F-B74B-12884F25292E} was invalid (~__/06/1947) - changed it to ~01/06/1947
The date for document with OID {BC0687B2-629E-4498-BD7E-592EDAD404A1} was invalid (~__/02/1947) - changed it to ~01/02/1947
The date for document with OID {BC0687B2-629E-4498-BD7E-592EDAD404A1} was invalid (~__/02/1947) - changed it to ~01/02/1947
Skipping document 4/125 with OID {10F4448C-EB47-486C-84D1-4E4269DA4AA3} because it's missing its XML file!! (stt exists: False)
Skipping document 5/125 with OID {EB75D4BA-E7A8-49EA-903E-9F876FBBF3B5} because it's missing its XML file!! (stt exists: False)
Skipping document 6/125 with OID {E5E5197A-3AB8-44F1-AA0C-A8F06EF7101D} because it's missing its XML file!! (stt exists: False)
Skipping document 7/125 with OID {C3BB5A60-4693-4A45-A4AD


Starting extracting 120 documents for program enquest
Skipping document 87/120 with OID {3055598F-87D5-4120-8F2D-F6570E49D3AB} because it's missing its XML file!! (stt exists: False)
Skipping document 94/120 with OID {59B38FA9-976E-4E14-87A8-172935248216} because it's missing its XML file!! (stt exists: False)
Skipping document 96/120 with OID {345F9ED0-471C-4C54-ADB9-3D6706F84EBF} because it's missing its XML file!! (stt exists: False)
The date for document with OID {18490C22-82F5-4AC3-9451-E1EFB2D9F100} was invalid (__/__/1979) - changed it to 01/01/1979


Skipping document 117/120 with OID {553708D4-F74C-4522-8275-CCB9E42B0F95} because it's missing its XML file!! (stt exists: False)
Skipping document 118/120 with OID {E00B1CB8-651F-414D-9896-5D6BEF5FACCD} because it's missing its XML file!! (stt exists: False)
enquest - returning 115 documents, 5 were skipped due to missing necessary info.

Starting extracting 998 documents for program enquest
Skipping document 4/998 with OID {35D79AA6-B71C-4887-AC82-6874D4134D48} because it's missing its XML file!! (stt exists: True)
The date for document with OID {F3A9B93C-30EE-4560-881E-3E0778370132} was invalid (__/10/1981) - changed it to 01/10/1981
Skipping document 109/998 with OID {62B32C4F-DDEB-42FC-A99A-8297997F809B} because it's missing its XML file!! (stt exists: True)
The date for document with OID {5A457892-5EAE-4E93-8BFB-45285816A589} was invalid (__/__/1979) - changed it to 01/01/1979
The date for document with OID {5A457892-5EAE-4E93-8BFB-45285816A589} was invalid (__/__/1979) - changed

100%|██████████| 2/2 [00:04<00:00,  2.09s/it]
11it [00:07,  1.45s/it]

The date for document with OID {69A42ABD-196A-408E-9369-327E5455D3F5} was invalid (__/__/1975) - changed it to 01/01/1975
enquest - returning 996 documents, 2 were skipped due to missing necessary info.
 --> Adding 1111 to the out csv for enquest

PROCESSING PROGRAM forum (12/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00,  2.54it/s]


Starting extracting 80 documents for program forum
Skipping document 2/80 with OID {B8B2EA61-7318-4C0F-A748-928C386C5C8F} because it's missing its XML file!! (stt exists: True)
Skipping document 7/80 with OID {1464A07B-A546-4B1B-9D1D-A2A4128AF91A} because it's missing its XML file!! (stt exists: False)
Skipping document 12/80 with OID {19B465C2-5832-4449-972A-0E2E94D801EC} because it's missing its XML file!! (stt exists: False)
Skipping document 13/80 with OID {B8B87301-D321-4BFF-85FD-58224B6FDBAD} because it's missing its XML file!! (stt exists: False)
Skipping document 14/80 with OID {35B50FC5-6425-44BB-94C7-6131E70314B4} because it's missing its XML file!! (stt exists: False)
Skipping document 15/80 with OID {D8A84F6F-DE38-4D90-BCD7-3CE387910F12} because it's missing its XML file!! (stt exists: False)
Skipping document 16/80 with OID {96ECDEB5-270E-4BA0-90B8-4CEF8354716A} because it's missing its XML file!! (stt exists: True)
Skipping document 19/80 with OID {EE0132B8-F3A0-4FBE-81C


12it [00:08,  1.18s/it]

 --> Adding 47 to the out csv for forum

PROCESSING PROGRAM forum_lau (13/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
13it [00:08,  1.14it/s]


Starting extracting 28 documents for program forum_lau
Skipping document 2/28 with OID {7C1DE208-F419-4484-9489-AED83DD6B1F0} because it's missing its XML file!! (stt exists: False)
Skipping document 3/28 with OID {F11EBA74-C46B-431C-9D7D-BF1ED2A4BCE9} because it's missing its XML file!! (stt exists: False)
Skipping document 4/28 with OID {CD9F154A-2878-451A-8FB5-F34E70D350BB} because it's missing its XML file!! (stt exists: False)
Skipping document 5/28 with OID {86A033D0-646C-4A86-B05E-FF262329F637} because it's missing its XML file!! (stt exists: False)
Skipping document 6/28 with OID {62AA878D-49E0-4FC0-8B20-182966FAE995} because it's missing its XML file!! (stt exists: False)
Skipping document 7/28 with OID {BB0F80E8-03D3-42D0-AE2D-20CE880262D7} because it's missing its XML file!! (stt exists: False)
Skipping document 8/28 with OID {C175FE3A-3714-48CC-8C1C-A478E4784711} because it's missing its XML file!! (stt exists: False)
Skipping document 10/28 with OID {EA2B2B6D-05F9-42CD-96


Starting extracting 29 documents for program geneve_info
Skipping document 7/29 with OID {4BA4914F-E47C-46B5-A511-FE934E4BCBED} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {F4C49936-ADB8-4332-B191-0FED38AD182F}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': 'F4C49936-ADB8-4332-B191-0FED38AD182F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F4C49936-ADB8-4332-B191-0FED38AD182F}', 'stripped_OID': 'F4C49936-ADB8-4332-B191-0FED38AD182F', 'login': '', 'broadcast_episode_title': "Interview de Charles Towns; professeur de physique ? l'universit? Columbia (2/2) : Exp?rience pr?vue avec l'horloge atomique sur les origines de l'univers", 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '19.03.2020 15:32:41', 'physical_support_hist

100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
14it [00:08,  1.53it/s]

Did not find any date for doc with OID {C48C7DCD-9127-40E1-81FD-E37A130B4376}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': 'C48C7DCD-9127-40E1-81FD-E37A130B4376_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C48C7DCD-9127-40E1-81FD-E37A130B4376}', 'stripped_OID': 'C48C7DCD-9127-40E1-81FD-E37A130B4376', 'login': '', 'broadcast_episode_title': 'La troisi?me force : Commentaire Alexandre Metaxas, journaliste', 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '03.02.2020 12:01:48', 'physical_support_history': "Cote d'origine: MA 58.38 PL. G.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Les pays qui constituent ce groupe souhaiteraient service d'interm?diai


Starting extracting 9 documents for program hist_ondes
Skipping document 5/9 with OID {7748497C-639B-491F-8B16-61762F50386D} because it's missing its XML file!! (stt exists: False)
Skipping document 6/9 with OID {68734C5E-1721-4E8A-8C7A-D13CE1B68053} because it's missing its XML file!! (stt exists: False)


100%|██████████| 1/1 [00:00<00:00, 18.17it/s]


hist_ondes - returning 7 documents, 2 were skipped due to missing necessary info.
 --> Adding 7 to the out csv for hist_ondes

PROCESSING PROGRAM infopile (16/47) - 1 files:



Starting extracting 198 documents for program infopile
Skipping document 1/198 with OID {7E1453BE-3EF7-423B-9147-BE25DC3348E9} because it's missing its XML file!! (stt exists: True)
Skipping document 7/198 with OID {C5AF20CA-9699-455B-A8AD-2847051D73A1} because it's missing its XML file!! (stt exists: False)
Skipping document 8/198 with OID {1331710F-85D5-4767-87E4-3F9172A92C64} because it's missing its XML file!! (stt exists: False)
Skipping document 9/198 with OID {00D21B01-8F78-4F8A-AA3C-1ABC07F8BB93} because it's missing its XML file!! (stt exists: False)
Skipping document 10/198 with OID {DC22379F-AAEF-4591-952E-1EAC3FC12A2A} because it's missing its XML file!! (stt exists: False)
Skipping document 11/198 with OID {81429DE6-4E49-46E8-933B-54670E811A89} because it's missing its XML file!! (stt exists: False)
Skipping document 13/198 with OID {1BDD195F-BDCA-4894-9E9F-19F7ADBACC63} because it's missing its XML file!! (stt exists: True)
Skipping document 15/198 with OID {F4AF053D-F91

100%|██████████| 1/1 [00:00<00:00,  1.50it/s]
16it [00:09,  1.89it/s]

Skipping document 125/198 with OID {70EFE7AD-70C7-425B-9217-02434908BA65} because it's missing its XML file!! (stt exists: False)
Skipping document 126/198 with OID {1CAD9E88-0B2E-4111-8527-9D544F2F4008} because it's missing its XML file!! (stt exists: True)
Skipping document 129/198 with OID {839F1D00-4E23-4579-BD70-C471C8D62064} because it's missing its XML file!! (stt exists: True)
Skipping document 131/198 with OID {86B6CEFD-E698-4FFA-9A46-C8E89B56CF1C} because it's missing its XML file!! (stt exists: True)
Skipping document 132/198 with OID {B67DE574-3316-4380-96F1-D26F1F3BCFB1} because it's missing its XML file!! (stt exists: True)
Skipping document 135/198 with OID {DDA58DDA-6931-4ECA-BEAE-EBE8169242AF} because it's missing its XML file!! (stt exists: False)
Skipping document 137/198 with OID {9416A745-4837-4990-897A-A6A2D95FE523} because it's missing its XML file!! (stt exists: False)
Skipping document 139/198 with OID {54D040F0-6BA7-402B-8F2F-821C199B2BCD} because it's missing


Starting extracting 581 documents for program inst_monde
Did not find any date for doc with OID {0B62FCAF-6201-4A70-BAE6-8452641F5418}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '0B62FCAF-6201-4A70-BAE6-8452641F5418_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{0B62FCAF-6201-4A70-BAE6-8452641F5418}', 'stripped_OID': '0B62FCAF-6201-4A70-BAE6-8452641F5418', 'login': '', 'broadcast_episode_title': "10?me anniversaire de l'Organisation europ?enne de coop?ration ?conomique (OECE) : D?claration de Max Petitpierre, conseiller f?d?ral neuch?telois", 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '31.10.2016 14:10:55', 'physical_support_history': "Cote d'origine: MA 58.9", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_stat

100%|██████████| 1/1 [00:02<00:00,  2.14s/it]
17it [00:11,  1.06it/s]

Skipping document 520/581 with OID {1574F9D6-1A6C-42DD-B309-1BF707571F6E} because it's missing its XML file!! (stt exists: False)
Skipping document 523/581 with OID {DBEFFA3B-1632-449B-9D2E-B0DB13CFE95D} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C}', 'stripped_OID': '69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C', 'login': '', 'broadcast_episode_title': "R?cit de l'accident de voiture de Fran?oise Sagan : Interview d'un passager de la voiture, ami de Fran?oise Sagan", 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '22.11.2016 20

100%|██████████| 1/1 [00:00<00:00,  2.17it/s]
18it [00:11,  1.22it/s]


Starting extracting 90 documents for program j13h
Did not find any date for doc with OID {E9DF5F99-0E1A-4618-B254-FCC1B7806882}. Trying to use the recording date. doc_dict: {'alias': 'j13h', 'date_str': None, 'stt_filename': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E9DF5F99-0E1A-4618-B254-FCC1B7806882}', 'stripped_OID': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882', 'login': '', 'broadcast_episode_title': 'Interview d\'Alfred Willener : Son rapport intitul� "La situation sociologique des m�dias en Suisse : Communications �mancipatrices?', 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '28.05.2022 06:00:35', 'physical_support_history': "Cote d'origine : A 3027", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': None, 'rights_status': 'Clarifi�', 


Starting extracting 66 documents for program j13h2


100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
19it [00:12,  1.43it/s]

Did not find any date for doc with OID {E9DF5F99-0E1A-4618-B254-FCC1B7806882}. Trying to use the recording date. doc_dict: {'alias': 'j13h2', 'date_str': None, 'stt_filename': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E9DF5F99-0E1A-4618-B254-FCC1B7806882}', 'stripped_OID': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882', 'login': '', 'broadcast_episode_title': 'Interview d\'Alfred Willener : Son rapport intitul� "La situation sociologique des m�dias en Suisse : Communications �mancipatrices?', 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '28.05.2022 06:00:35', 'physical_support_history': "Cote d'origine : A 3027", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': None, 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': 'Concepti


Starting extracting 0 documents for program j_mat
j_mat - returning 0 documents, 0 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 1/999 with OID {26ED9EB6-C7C9-4056-88A8-FB0FBF8B0915} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {9F3AE870-279E-45B9-9F8F-1B6400A2A04D} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {1CEE59EC-D842-49CF-B56A-2A4A6DCEE493} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {71974CAA-7079-455C-8F73-0C8C2B4255CD} because it's missing its XML file!! (stt exists: True)
Skipping document 5/999 with OID {6729CC58-BD78-456C-B8C1-90A9B233D88F} because it's missing its XML file!! (stt exists: True)
Skipping document 6/999 with OID {28755BC1-3D12-4FC3-9247-3DF5DC8125A3} because it's missing its XML file!! (stt exists: True)
Skipping document 7/999 with OID {DC5CFE35-ABFB-4319-9

Skipping document 901/999 with OID {A426DEEE-68C1-4987-A4E4-2E47BA086AB1} because it's missing its XML file!! (stt exists: False)
Skipping document 902/999 with OID {8495A7E9-7DCE-4389-BA64-962EA7D44057} because it's missing its XML file!! (stt exists: False)
Skipping document 903/999 with OID {B7C4B81A-D1FF-4DC7-9529-CB5EB9A6D0A8} because it's missing its XML file!! (stt exists: False)
Skipping document 904/999 with OID {9236BE44-6CA9-474B-85C8-A78C51418A46} because it's missing its XML file!! (stt exists: False)
Skipping document 907/999 with OID {7D0721AE-EA44-4C86-97FD-B99CF5F1BC10} because it's missing its XML file!! (stt exists: False)
Skipping document 914/999 with OID {CB69F524-D0F0-4154-BDBE-96ACBB559A84} because it's missing its XML file!! (stt exists: False)
Skipping document 917/999 with OID {6F69DAE7-0B09-4366-9F80-8091F6A25E71} because it's missing its XML file!! (stt exists: True)
Skipping document 920/999 with OID {D503CCC6-A8F2-4C6C-8D63-194D465A32F3} because it's miss

Skipping document 902/999 with OID {4FD146D6-0100-48CA-BB9A-80C4BA08DD3F} because it's missing its XML file!! (stt exists: False)
Skipping document 903/999 with OID {99682EB6-E4B8-4154-BD64-A6394BD2BE35} because it's missing its XML file!! (stt exists: False)
Skipping document 906/999 with OID {81D7D191-4789-4682-A851-3C619C4A0EE1} because it's missing its XML file!! (stt exists: False)
Skipping document 920/999 with OID {FBBE3C74-78B4-493E-95BC-F098F5C20D83} because it's missing its XML file!! (stt exists: True)
Skipping document 924/999 with OID {9A866C74-4544-4543-BE22-89A1FCB37AFA} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {13CA4A81-F13D-4F5C-A8E6-3E37590F3292} because it's missing its XML file!! (stt exists: False)
Skipping document 932/999 with OID {6F134BBF-67A2-419D-A039-4754C01CB6A3} because it's missing its XML file!! (stt exists: False)
Skipping document 933/999 with OID {3F0EAC87-44B8-4845-8A83-A1D5A85B9AF3} because it's miss

Skipping document 989/999 with OID {0B9B6C16-A743-488F-9F2D-48A331661F66} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {5F5D1320-BE5B-48A3-A6F3-8AD5B832E747} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {E646270A-2370-4A25-80B8-219829667222} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {B7B8E55A-1F9C-4897-9B2D-40B632759F92} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {27234CBE-7304-4552-8C16-A37849720FA0} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {34FBB968-3208-47BE-AAD5-1C605100A08A} because it's missing its XML file!! (stt exists: True)
j_mat - returning 650 documents, 349 were skipped due to missing necessary info.

Starting extracting 998 documents for program j_mat
Skipping document 2/998 with OID {F378A6EF-2FAF-4FBD-95D9-B0CC03272469} because it's mi

Skipping document 987/998 with OID {8586E6C9-B899-4F4C-859E-5327B39AC2EC} because it's missing its XML file!! (stt exists: False)
Skipping document 992/998 with OID {211C0425-D479-45E1-A722-ED1F715F8E54} because it's missing its XML file!! (stt exists: False)
Skipping document 993/998 with OID {4E40C48E-DF75-482B-855A-A41DF3214B9F} because it's missing its XML file!! (stt exists: False)
Skipping document 994/998 with OID {9F981A76-4E2F-49B1-89F4-225533807ED3} because it's missing its XML file!! (stt exists: False)
j_mat - returning 660 documents, 338 were skipped due to missing necessary info.

Starting extracting 998 documents for program j_mat
Skipping document 3/998 with OID {849599D0-AB9B-4B5D-8A47-D28DBA2C2EE6} because it's missing its XML file!! (stt exists: False)
Skipping document 6/998 with OID {F7CD3758-1220-4E94-BA43-08760579076D} because it's missing its XML file!! (stt exists: False)
Skipping document 7/998 with OID {39642BCC-3126-48CB-AB4A-1446004B188C} because it's missi

Skipping document 982/998 with OID {086C7EF5-DBB7-4D11-9E8E-A4699440E574} because it's missing its XML file!! (stt exists: False)
Skipping document 983/998 with OID {1C34AA0B-FCCB-404F-9031-676398E0BAA2} because it's missing its XML file!! (stt exists: False)
Skipping document 985/998 with OID {C4C044FC-FC58-4D2E-AB42-4CE7C444EA73} because it's missing its XML file!! (stt exists: False)
Skipping document 986/998 with OID {9C783E2D-A6D1-4E36-A7A3-03321B7D3D27} because it's missing its XML file!! (stt exists: False)
Skipping document 987/998 with OID {25233384-1BC0-467B-A85F-74364B205F40} because it's missing its XML file!! (stt exists: False)
Skipping document 988/998 with OID {6B3212DE-F8A3-4720-A03D-0091DAFBB179} because it's missing its XML file!! (stt exists: False)
Skipping document 989/998 with OID {AA118050-40C9-4E44-9901-B5178C64ECE1} because it's missing its XML file!! (stt exists: False)
Skipping document 994/998 with OID {F4E8A3A3-04BC-4B6E-8719-28CFA9DED581} because it's mis

Skipping document 308/323 with OID {E486D578-D5A0-42C6-9214-A0873EA386A5} because it's missing its XML file!! (stt exists: True)
Skipping document 309/323 with OID {A9841B99-1B6A-42FD-B2E0-892009A10145} because it's missing its XML file!! (stt exists: True)
Skipping document 310/323 with OID {B9A1736E-3766-431B-BE68-0E72FBA4DBE3} because it's missing its XML file!! (stt exists: True)
Skipping document 311/323 with OID {67EC1637-0F0A-4C3B-A3E0-43502789C8D5} because it's missing its XML file!! (stt exists: True)
Skipping document 312/323 with OID {E9BEC593-E4AB-443A-A0A5-DAC2E69EC352} because it's missing its XML file!! (stt exists: True)
Skipping document 313/323 with OID {72A9D610-88D1-4370-88D1-60C6B08B3412} because it's missing its XML file!! (stt exists: True)
Skipping document 317/323 with OID {62FC7E3F-3D2D-46BE-B6FA-0DD5273DA49A} because it's missing its XML file!! (stt exists: False)
Skipping document 319/323 with OID {A795C480-4FBC-4ECF-9D17-80C2A7FB934E} because it's missing i

Skipping document 987/999 with OID {D25DB230-8095-42DE-848E-162E75D56E62} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {AB171598-DA2C-466F-B4E3-E2BC5B2B562D} because it's missing its XML file!! (stt exists: False)
Skipping document 989/999 with OID {7800BAB2-0000-445D-883C-11C7DBD0A0AD} because it's missing its XML file!! (stt exists: True)
Skipping document 992/999 with OID {ACA4AFB2-E29F-45EE-9BC1-CC60EBE501FA} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {43796C3E-09C9-481D-9BCB-AB9B4B79E414} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {95FDBF59-D18B-45A9-A6E0-7D02441D8B3A} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {0EAEF454-967B-4BB4-A8DC-4C5FF4416645} because it's missing its XML file!! (stt exists: True)
j_mat - returning 652 documents, 347 were skipped due to missing necessary info.

Starting e

Skipping document 955/999 with OID {960DE70F-C64E-4752-8064-456ACD28756D} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {5D1217CF-7A31-491A-9E80-BC305DD09C20} because it's missing its XML file!! (stt exists: False)
Skipping document 957/999 with OID {07CAE8C1-09A4-4121-90C4-7B3181124DE7} because it's missing its XML file!! (stt exists: False)
Skipping document 960/999 with OID {27E4F311-8F5B-40FA-91C9-B818B4FC627B} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {9450D488-BA00-4529-B998-603E30BC4978} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {649352B4-EB28-41E9-ADF5-F270FF72C846} because it's missing its XML file!! (stt exists: False)
Skipping document 973/999 with OID {442A111E-249B-4D3D-BC04-24490B7D8DEE} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {495C526E-0105-485C-ACB0-3A2B613B58A1} because it's mis

100%|██████████| 11/11 [00:33<00:00,  3.08s/it]

Skipping document 926/999 with OID {91A71D4F-26A6-4119-9C2A-9733ECD8E0C1} because it's missing its XML file!! (stt exists: True)
Skipping document 927/999 with OID {828677C5-8E4A-4F80-8B7A-E9F25D95435A} because it's missing its XML file!! (stt exists: True)
Skipping document 928/999 with OID {D19A071E-40E0-411A-AACD-3AD19A495BAB} because it's missing its XML file!! (stt exists: False)
Skipping document 940/999 with OID {1A6500AE-9F81-4B1E-BDD9-27C093CE06E6} because it's missing its XML file!! (stt exists: False)
Skipping document 945/999 with OID {9FCC11EE-90F0-4E1C-BA21-9B95627AD255} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {53305BC9-4215-4BC7-99FC-604CABE62262} because it's missing its XML file!! (stt exists: False)
Skipping document 949/999 with OID {5E1121E9-E87C-499E-829A-E403D0523B05} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {5422907B-4B59-4649-920B-3E775718937C} because it's missi


20it [00:48, 10.67s/it]


PROCESSING PROGRAM j_midi (21/47) - 7 files:



Starting extracting 999 documents for program j_midi
Skipping document 1/999 with OID {9A8DAD76-EC7F-432E-9FFF-A7C09F5BB3B8} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {13F9BA24-7277-4A92-B7E9-6E9C695C01AD} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {9BCF38D9-7FBF-4A4E-8193-1AFD519A9B38} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {E24CCE52-F76F-45D4-98D8-498AEC8701CA} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {A066D541-E9E5-4F2B-807E-FC596B570553} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {31700ABD-27CB-46B6-96F5-7C5BD1703987} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {52F80052-8B34-47EC-AFDC-885037ADB671} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {87B0C497-F6A

Skipping document 939/999 with OID {75CB15CD-AC86-4C03-BDEA-8C1B28374C86} because it's missing its XML file!! (stt exists: False)
Skipping document 942/999 with OID {940235A5-C088-4E58-A413-07D882946B2E} because it's missing its XML file!! (stt exists: False)
Skipping document 946/999 with OID {C8B2DB73-0799-4AD6-80E8-58879D055ABD} because it's missing its XML file!! (stt exists: True)
Skipping document 949/999 with OID {D2535814-405A-4B65-9700-8C1817A2C8F6} because it's missing its XML file!! (stt exists: False)
Skipping document 951/999 with OID {50A9B154-A089-42F7-8AC3-757A501DA699} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {D1AA4F7A-493F-4866-8437-F37088A7B4A9} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {BF7D6B4F-C0CD-409F-BEB8-AAE13979A721} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {E7F71A28-2CAA-4626-B195-CA083D651DCD} because it's miss

Skipping document 890/999 with OID {E064CF7C-9226-4CC9-B884-5B4CDE00A4DA} because it's missing its XML file!! (stt exists: True)
Skipping document 891/999 with OID {BAA1CC00-724C-49E6-8481-995A3E53C047} because it's missing its XML file!! (stt exists: False)
Skipping document 892/999 with OID {46D99342-1E13-4264-9E80-7AF10DA15F4C} because it's missing its XML file!! (stt exists: False)
Skipping document 893/999 with OID {DA3E9417-A605-41E2-B391-A629D957781F} because it's missing its XML file!! (stt exists: False)
Skipping document 894/999 with OID {83BABC6B-4B76-48BE-A57E-483FC258D971} because it's missing its XML file!! (stt exists: False)
Skipping document 897/999 with OID {1AAAA513-9E94-4B97-8142-D1A4637F080F} because it's missing its XML file!! (stt exists: False)
Skipping document 901/999 with OID {4C0DA78A-6F76-4E50-AD50-E5B297AEA6AB} because it's missing its XML file!! (stt exists: False)
Skipping document 904/999 with OID {A18CEB6C-7F57-4633-BE58-9C5C0EF4A7DC} because it's miss

Skipping document 979/999 with OID {32C26A44-6293-499A-A2D3-801311F060B1} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {9D0B1328-C03F-4D9E-80FD-99382E4E2277} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {E09FCAF3-22C7-473B-B0E7-DDA0F5580EA1} because it's missing its XML file!! (stt exists: False)
Skipping document 982/999 with OID {1FDA1936-E5DC-4EB1-9E63-DFB0F68B7CB7} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {32D64EFA-DB69-4FD5-B0BE-E8A88E68C68F} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {061074B8-2D8E-483E-8805-FD190D49EF28} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {1D1235E5-240D-41BB-BAD3-261AF96ADA8F} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {6178E64F-CADD-415F-80F1-13E740DD7D9D} because it's mis

Skipping document 977/999 with OID {313D6B4B-CFE0-4680-9017-CF1EB9EEDA7E} because it's missing its XML file!! (stt exists: False)
Skipping document 979/999 with OID {49E96F58-0BC0-476A-A950-5CECE9D2F49A} because it's missing its XML file!! (stt exists: True)
Skipping document 984/999 with OID {5A8DECF9-6F99-49E4-8F05-FA589492535C} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {091BA2DA-9708-43D2-9E2E-6DA7D6757845} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {B0E4345E-75AC-4F08-B0DA-892D3608E4D0} because it's missing its XML file!! (stt exists: True)
Skipping document 994/999 with OID {47B01321-E8E0-42F9-9C44-90E6526E470A} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {FA9B2E71-5BE6-4791-A6E4-6895E1D0ABCF} because it's missing its XML file!! (stt exists: True)
Skipping document 996/999 with OID {5622D1D2-7778-47B0-8CFC-12162B3E910A} because it's missin

Skipping document 926/999 with OID {A08350B0-851C-4B48-BFC6-374816A8DD3E} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {821DE259-9214-4680-AD24-035BB3C91E3F} because it's missing its XML file!! (stt exists: True)
Skipping document 929/999 with OID {C6455B34-4506-4D2A-9C6F-04AE30CD6B34} because it's missing its XML file!! (stt exists: False)
Skipping document 931/999 with OID {CFFFCDD7-9E93-4769-8BEA-2909CDA7CEB2} because it's missing its XML file!! (stt exists: False)
Skipping document 935/999 with OID {40F75BEF-19AC-44B7-AF1E-E22D66B2F804} because it's missing its XML file!! (stt exists: False)
Skipping document 938/999 with OID {D5208033-7B82-4C64-8E20-BDF811C6668B} because it's missing its XML file!! (stt exists: False)
Skipping document 940/999 with OID {FB7FB926-9943-41EE-A5AF-62E6130F87AB} because it's missing its XML file!! (stt exists: True)
Skipping document 942/999 with OID {CA7F4387-2FC8-4801-B954-22575D814445} because it's missi

Skipping document 411/418 with OID {BBCED5EE-69E3-46FB-BA02-F92DF602FE30} because it's missing its XML file!! (stt exists: True)
Skipping document 414/418 with OID {66A51CF7-8033-4D67-A3DA-AD03ABF22D3B} because it's missing its XML file!! (stt exists: True)
Skipping document 418/418 with OID {BF31431D-F34C-4884-9CD1-BDA96E76471D} because it's missing its XML file!! (stt exists: True)
j_midi - returning 291 documents, 127 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_midi
Skipping document 2/999 with OID {5C81CE34-8235-452F-A8D4-2CEBED726B14} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {3F5E2CBB-1635-4D68-94DF-47E89C5E3F6C} because it's missing its XML file!! (stt exists: False)
Skipping document 5/999 with OID {1F607EA8-B8C2-468C-92DF-B0313F6AA9EF} because it's missing its XML file!! (stt exists: True)
Skipping document 6/999 with OID {098D07E4-48C9-442D-9775-5C95474618EF} because it's missing i

100%|██████████| 7/7 [00:25<00:00,  3.60s/it]

Skipping document 925/999 with OID {BE05F3C2-DB3A-4F75-8723-FD9C4A309F25} because it's missing its XML file!! (stt exists: False)
Skipping document 926/999 with OID {AEF84014-6F75-4E13-B131-BAF7145734D8} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {CBE81CAD-FC13-43C2-93E6-A9753F9D7FB9} because it's missing its XML file!! (stt exists: True)
Skipping document 934/999 with OID {2287776F-0223-4CA5-BEE2-D25C82C9BB31} because it's missing its XML file!! (stt exists: False)
Skipping document 938/999 with OID {CCC88B8F-024F-41D3-9730-1C6C54E0E7CE} because it's missing its XML file!! (stt exists: False)
Skipping document 944/999 with OID {075CD766-E9A8-4D97-A72B-5189A81811BC} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {47192059-AB51-47A5-A00B-6C18E932CC1F} because it's missing its XML file!! (stt exists: False)
Skipping document 951/999 with OID {DAA737B4-A669-4BCE-A558-0D83D0A1B7D6} because it's miss


21it [01:15, 15.38s/it]


PROCESSING PROGRAM j_nuit (22/47) - 1 files:


100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
22it [01:16, 10.99s/it]


Starting extracting 35 documents for program j_nuit
Skipping document 1/35 with OID {7E1D0E93-ABEC-4578-9562-9F8014747173} because it's missing its XML file!! (stt exists: False)
Skipping document 2/35 with OID {EFDEA34F-913A-472A-9BBB-3FBADD88628C} because it's missing its XML file!! (stt exists: False)
Skipping document 6/35 with OID {E40023C5-247C-498F-B800-0E2BE4F8D082} because it's missing its XML file!! (stt exists: False)
Skipping document 7/35 with OID {F9325037-0119-4571-8FB9-D05CFA61C915} because it's missing its XML file!! (stt exists: True)
Skipping document 9/35 with OID {4ABA159F-6A72-4C82-A1A9-2D3615D2189B} because it's missing its XML file!! (stt exists: False)
Skipping document 10/35 with OID {674F05E6-1283-4E82-BB42-25ABB8C2EE3B} because it's missing its XML file!! (stt exists: True)
Skipping document 17/35 with OID {7A59CC55-3879-4BEB-B329-2867500FC1A2} because it's missing its XML file!! (stt exists: False)
Skipping document 18/35 with OID {9F466BFB-BA3E-4134-8AAE-


Starting extracting 999 documents for program j_soir
Skipping document 2/999 with OID {1FA80336-ACBF-49C7-9DB2-39D255A66187} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {C36D5146-6E66-431B-A487-0130E43DBB8F} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {26FD5AB7-0E2C-42CB-B190-78B6AEC08F43} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {E7DACDF7-D579-48D3-AC76-BF94A39793C0} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {7BE6AE82-31FA-450A-9168-50CBCA4437B7} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {E7E62159-6D0A-460F-8AC0-5EC0F77A0FD5} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {8A906148-4A41-477C-988F-A3D194438C88} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {70AB66A7-5D5F

Skipping document 959/999 with OID {079CFE6A-C699-459F-95C3-A71FBCC36A70} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {005B8200-7DF0-4015-B851-2DA193D70C37} because it's missing its XML file!! (stt exists: True)
Skipping document 963/999 with OID {9F25FEE8-F069-49EA-BDA2-CF46B8C1575A} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {207325E3-F25F-44B1-BD08-C2321B274853} because it's missing its XML file!! (stt exists: False)
Skipping document 975/999 with OID {6FE044B4-CF8A-49E7-8B8D-15197EDCD1D6} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {C6A9A08E-20A9-4ED4-92F2-E2702E444CBE} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {06C7AA23-EC61-45F7-B008-9BE58A8981DE} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {A945506D-4863-467C-A33F-880FA35AD01B} because it's miss

Skipping document 886/999 with OID {6C510E2B-F153-487F-B3BD-604A1580AD50} because it's missing its XML file!! (stt exists: False)
Skipping document 896/999 with OID {D615A75D-9DAC-4DD3-B5C6-C4B972D241F8} because it's missing its XML file!! (stt exists: False)
Skipping document 901/999 with OID {F1D3493B-5EE1-4298-B681-4862B8B93C83} because it's missing its XML file!! (stt exists: False)
Skipping document 903/999 with OID {D0510A69-69F6-4E5D-A6D2-01543AF0CF9A} because it's missing its XML file!! (stt exists: False)
Skipping document 905/999 with OID {CF2E37BB-657C-481A-A64D-57CE9DB5C42D} because it's missing its XML file!! (stt exists: False)
Skipping document 906/999 with OID {92E26A3D-AA70-4570-96FA-20921CD2456E} because it's missing its XML file!! (stt exists: False)
Skipping document 910/999 with OID {E3CC476A-25AF-4CD0-9C80-AE68F945AEA1} because it's missing its XML file!! (stt exists: False)
Skipping document 913/999 with OID {E94FC474-4464-4775-A8AA-F95F13607D50} because it's mis

Skipping document 925/999 with OID {73329ADB-E3EC-4CC1-907E-6409EFD57514} because it's missing its XML file!! (stt exists: False)
Skipping document 937/999 with OID {88560D57-1B03-49CD-A52E-9C5E127CC456} because it's missing its XML file!! (stt exists: False)
Skipping document 939/999 with OID {44FFFFE7-B6A5-42E2-BFD9-7EEA2CA9EAC3} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {5EFC9B28-76CA-4F1D-A5FD-7B79C0B099EC} because it's missing its XML file!! (stt exists: False)
Skipping document 948/999 with OID {863FFE97-4F6A-451D-8126-BDFABCEDEC26} because it's missing its XML file!! (stt exists: False)
Skipping document 949/999 with OID {557DA3D7-E53F-4EC9-AC12-B04DCD2F8F44} because it's missing its XML file!! (stt exists: False)
Skipping document 950/999 with OID {7D827E1D-B7FD-4CD2-B76A-003715B6F703} because it's missing its XML file!! (stt exists: False)
Skipping document 952/999 with OID {8C452457-7F86-49F1-A1C9-7B457B3091A2} because it's mis

Skipping document 914/999 with OID {ED41E9D5-9DAF-48C4-A02F-3D47BB0FA348} because it's missing its XML file!! (stt exists: False)
Skipping document 917/999 with OID {25F14D80-8821-4624-81B6-CED91CBF6E7D} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {EF66873F-C9C8-4354-910A-3413E0D42BCB}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'EF66873F-C9C8-4354-910A-3413E0D42BCB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{EF66873F-C9C8-4354-910A-3413E0D42BCB}', 'stripped_OID': 'EF66873F-C9C8-4354-910A-3413E0D42BCB', 'login': '', 'broadcast_episode_title': 'Elections f?d?rales. Interview de Mario Soldini, conseiller national genevois, sur la r?partition des si?ges au Conseil national', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'dupasqbl', 'modified_on': '24.0

Skipping document 963/999 with OID {8E073D50-2D10-4B76-BC59-E86A4ABA970F} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {6132571F-7DB4-460D-A7C8-78EE1C2E83EE} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {A1E2358C-1304-466B-B9B4-B8B6381BA388} because it's missing its XML file!! (stt exists: False)
Skipping document 977/999 with OID {B6C62EBB-8AE4-4571-B6B8-3AE567AF4B4F} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {DC660BE2-5576-4A7B-8F32-46539A01F4E5} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {94F68FDF-F3C8-4384-B5D0-B67935C6CE2E} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {93FDD7C4-2C79-436F-82BF-319459740160} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {809CD216-18CF-4E0A-9F6D-5ACC2A9C9C35} because it's mis

Skipping document 992/999 with OID {6913ACEE-A0EA-4251-A1FA-CBC3177DD502} because it's missing its XML file!! (stt exists: True)
Skipping document 994/999 with OID {3FDF8B6A-047C-418F-B924-ED26F78AAD61} because it's missing its XML file!! (stt exists: True)
j_soir - returning 719 documents, 280 were skipped due to missing necessary info.

Starting extracting 998 documents for program j_soir
Skipping document 4/998 with OID {8DB402EC-CD29-430E-A690-AF6F0FB06202} because it's missing its XML file!! (stt exists: False)
Skipping document 5/998 with OID {641B1565-457F-4928-91A8-3AFE31D51B46} because it's missing its XML file!! (stt exists: False)
Skipping document 6/998 with OID {9DF2ED51-2A05-4D00-A405-9D40390EE577} because it's missing its XML file!! (stt exists: False)
Skipping document 7/998 with OID {1E9143AF-FE35-46D6-B134-85160CB31395} because it's missing its XML file!! (stt exists: False)
Skipping document 8/998 with OID {1A818A71-3FBA-4EDA-AED2-EC937A0EBED2} because it's missing i

Did not find any date for doc with OID {90132942-68A2-491A-94D1-2F89BAC33BF7}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '90132942-68A2-491A-94D1-2F89BAC33BF7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{90132942-68A2-491A-94D1-2F89BAC33BF7}', 'stripped_OID': '90132942-68A2-491A-94D1-2F89BAC33BF7', 'login': '', 'broadcast_episode_title': 'Caserne militaire de Colombier (Ne). Les jeunes recrues qui ont ing?r? 30 grammes de plastite sont hors de danger : Interview de Patrick Cudr?-Mauroux, porte-parole du DMF', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '30.05.2022 18:05:43', 'physical_support_history': "Cote d'origine : 21064 Pl. 05", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': None, 'rights_status': 'Clarifi?', 'se

100%|██████████| 8/8 [00:28<00:00,  3.62s/it]

Skipping document 222/291 with OID {010ABDF9-D54F-4B2C-A73B-28D35D4EE766} because it's missing its XML file!! (stt exists: False)
Skipping document 224/291 with OID {3F258717-165B-4489-88F2-B126266BE117} because it's missing its XML file!! (stt exists: False)
Skipping document 225/291 with OID {F810C92B-F28A-4BCB-B0DD-BCE31480AF48} because it's missing its XML file!! (stt exists: False)
Skipping document 228/291 with OID {48393D68-68E5-49CD-B530-D827822ACD00} because it's missing its XML file!! (stt exists: False)
Skipping document 238/291 with OID {9445A246-7B97-45A3-8F69-02DA2449912D} because it's missing its XML file!! (stt exists: False)
Skipping document 241/291 with OID {625CC25F-8887-4684-9E47-552219B0743C} because it's missing its XML file!! (stt exists: False)
Skipping document 243/291 with OID {11EA886E-2FDE-47EB-A49C-686D11061259} because it's missing its XML file!! (stt exists: False)
Skipping document 244/291 with OID {645106CA-3536-44BB-B3C5-DBC3CC3902BF} because it's mis


23it [01:47, 17.07s/it]


PROCESSING PROGRAM mag_eco (24/47) - 2 files:



Starting extracting 22 documents for program mag_eco
Skipping document 20/22 with OID {0B188853-0430-41C3-A41B-9B0B6202DB22} because it's missing its XML file!! (stt exists: False)
mag_eco - returning 21 documents, 1 were skipped due to missing necessary info.

Starting extracting 21 documents for program mag_eco


100%|██████████| 2/2 [00:00<00:00,  8.88it/s]
24it [01:48, 12.12s/it]

mag_eco - returning 21 documents, 0 were skipped due to missing necessary info.
 --> Adding 42 to the out csv for mag_eco

PROCESSING PROGRAM mag_info (25/47) - 2 files:



Starting extracting 999 documents for program mag_info
Skipping document 14/999 with OID {4D46DF11-E4F3-4BAB-B86D-FD1CC2188F07} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {E40D02FF-5B96-4122-BA3E-71D5D4883497} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {8D4E894D-0784-4C04-85C5-2FC996CD833C}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '8D4E894D-0784-4C04-85C5-2FC996CD833C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8D4E894D-0784-4C04-85C5-2FC996CD833C}', 'stripped_OID': '8D4E894D-0784-4C04-85C5-2FC996CD833C', 'login': '', 'broadcast_episode_title': '1. Interview de Simone Signoret, com?dienne. - 2. Interview de Yves Montand, com?dien', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo'

mag_info - returning 991 documents, 8 were skipped due to missing necessary info.

Starting extracting 772 documents for program mag_info
Skipping document 62/772 with OID {DD8F1682-D785-4881-858E-FD8F1666FDF5} because it's missing its XML file!! (stt exists: False)
Skipping document 100/772 with OID {D29E8A8F-5AC7-4479-861D-6FF413D77547} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {9E0FE0C9-737D-4E68-9B04-E67C925996E9}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '9E0FE0C9-737D-4E68-9B04-E67C925996E9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9E0FE0C9-737D-4E68-9B04-E67C925996E9}', 'stripped_OID': '9E0FE0C9-737D-4E68-9B04-E67C925996E9', 'login': '', 'broadcast_episode_title': "La situation en Allemagne de l'Est. L'heure des r?formes est-elle arriv?e?: 1. Indicatif de Radio-Glasnost, radio locale berlinoise de l'Ouest destin?e aux

100%|██████████| 2/2 [00:07<00:00,  3.83s/it]

Skipping document 693/772 with OID {641647ED-E17F-450F-80ED-6DB9DB87194B} because it's missing its XML file!! (stt exists: False)
Skipping document 760/772 with OID {C82B8342-DFA0-4F9A-9D1B-C211332493DB} because it's missing its XML file!! (stt exists: False)
mag_info - returning 764 documents, 8 were skipped due to missing necessary info.
 --> Adding 1755 to the out csv for mag_info



25it [01:56, 11.10s/it]


PROCESSING PROGRAM mag_sci1 (26/47) - 1 files:



Starting extracting 161 documents for program mag_sci1
Did not find any date for doc with OID {57686BE0-266E-4ADA-86AE-C44E99CF9ED4}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': '57686BE0-266E-4ADA-86AE-C44E99CF9ED4_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{57686BE0-266E-4ADA-86AE-C44E99CF9ED4}', 'stripped_OID': '57686BE0-266E-4ADA-86AE-C44E99CF9ED4', 'login': '', 'broadcast_episode_title': "1. Interview d'Aldo Fossati, sp?cialiste ? la station f?d?rale de Changins. - 2. Commentaire du physicien Jean Rossel. - 3. Interview du prix Nobel de m?decine Roger Guillemin. - 4. Interview des m?decins Peter de Graad et Pierre Cattan", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '11.09.2018 10:02:19', 'physical_support_history': "Cote d'origine: MA 86.100", 'production_t

100%|██████████| 1/1 [00:00<00:00,  1.19it/s]
26it [01:57,  8.08s/it]

Did not find any date for doc with OID {511F8FD1-D3CC-4C0B-B027-EC86B87BA507}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': '511F8FD1-D3CC-4C0B-B027-EC86B87BA507_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{511F8FD1-D3CC-4C0B-B027-EC86B87BA507}', 'stripped_OID': '511F8FD1-D3CC-4C0B-B027-EC86B87BA507', 'login': '', 'broadcast_episode_title': 'Interview de Robert Hainard, sculpteur, peintre et naturaliste : A propos de la r??dition de son ouvrage "D?fense de l\'image" (Ed- La Baconni?re" et de sa position face ? l\'art abstrait', 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences humaines', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '12.05.2022 21:14:29', 'physical_support_history': "Cote d'origine : MP 8661.a Resp. RSR : BBR Lot : Caisse 3146", 'production_type': 'Production propre', 'recording_place': None, 'rights

100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
27it [01:58,  5.75s/it]


Starting extracting 62 documents for program mag_sci2
Did not find any date for doc with OID {516065DB-5296-41C7-9AF7-E9B5A076C7EB}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci2', 'date_str': None, 'stt_filename': '516065DB-5296-41C7-9AF7-E9B5A076C7EB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{516065DB-5296-41C7-9AF7-E9B5A076C7EB}', 'stripped_OID': '516065DB-5296-41C7-9AF7-E9B5A076C7EB', 'login': '', 'broadcast_episode_title': "Interviee d'Hugo Thiemann, Maurice Paquet, Roger Lacroix : A propos de la recherche scientifique", 'sequence': '1', 'broadcast_program_name': 'Magazine de la science', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'RCR (NumA)', 'modified_on': '29.05.2022 05:00:20', 'physical_support_history': "Cote d'origine : MP 657.c Resp. RSR : RCR Lot : Caisse 3038", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', '

0it [00:00, ?it/s]


 --> Adding 0 to the out csv for mag_tv1

PROCESSING PROGRAM mag_tv2 (29/47) - 1 files:



Starting extracting 72 documents for program mag_tv2
Skipping document 1/72 with OID {CC7B9112-89B2-48F4-9A1A-4A57AC994F7B} because it's missing its XML file!! (stt exists: False)
Skipping document 2/72 with OID {23CA5B60-4C6C-414E-A37B-BFD79F76884B} because it's missing its XML file!! (stt exists: False)
Skipping document 5/72 with OID {52A89335-F61D-4884-85D1-346173D2C8CD} because it's missing its XML file!! (stt exists: False)
Skipping document 6/72 with OID {D93909A9-4CC9-4347-9B4A-2B4C9FC03151} because it's missing its XML file!! (stt exists: False)
Skipping document 7/72 with OID {AB266DA5-DB6C-4174-A737-FBE98A62609F} because it's missing its XML file!! (stt exists: False)
Skipping document 8/72 with OID {C09CAE17-02CA-42BB-BE9F-213DF51AF30D} because it's missing its XML file!! (stt exists: False)
Skipping document 9/72 with OID {FEBF832C-BF2D-47D0-9405-0EAB15501514} because it's missing its XML file!! (stt exists: False)
Skipping document 10/72 with OID {D57668E8-F1F6-4576-B2F2

100%|██████████| 1/1 [00:00<00:00,  3.72it/s]
29it [01:58,  3.17s/it]

Skipping document 16/72 with OID {67DC8B6C-878E-4F41-AA3C-8C8D8F1E3E67} because it's missing its XML file!! (stt exists: False)
Skipping document 17/72 with OID {E03DCECF-C05A-44F6-B939-7F2214212ACD} because it's missing its XML file!! (stt exists: False)
Skipping document 18/72 with OID {8E1FBEB9-26D8-4882-95E7-9106AD6A7E04} because it's missing its XML file!! (stt exists: False)
Skipping document 19/72 with OID {D55C947C-A3BF-4A2D-9E06-066ADECD3554} because it's missing its XML file!! (stt exists: False)
Skipping document 20/72 with OID {043AF4E8-A4F0-4E7A-A9CB-4BE2D022FC86} because it's missing its XML file!! (stt exists: False)
Skipping document 21/72 with OID {4FEEE59C-4861-42E2-8E5C-751E923CF389} because it's missing its XML file!! (stt exists: False)
Skipping document 22/72 with OID {71E77E43-12D8-4C21-97FD-1F04BC0948DE} because it's missing its XML file!! (stt exists: False)
Skipping document 23/72 with OID {E0B571C6-83F6-4F5C-8813-101307A573BF} because it's missing its XML fil


Starting extracting 95 documents for program mem_ondes
Skipping document 1/95 with OID {F96F2E2E-3E38-4840-9E21-535415D78768} because it's missing its XML file!! (stt exists: False)
Skipping document 11/95 with OID {CF570038-08F3-4B01-B869-5316291A261D} because it's missing its XML file!! (stt exists: False)
Skipping document 25/95 with OID {DAD396AC-77D3-437A-807F-E2A167A256FC} because it's missing its XML file!! (stt exists: False)
Skipping document 40/95 with OID {185156B1-88C9-45B8-A96A-114FCD5C002F} because it's missing its XML file!! (stt exists: False)
Skipping document 46/95 with OID {51E72952-65BF-4B0A-80A2-9DD14473882F} because it's missing its XML file!! (stt exists: False)
Skipping document 52/95 with OID {7CB48CC9-A595-41FD-A7CA-C18BB584E96E} because it's missing its XML file!! (stt exists: False)
Skipping document 60/95 with OID {BAF371B9-7F37-47AA-B8E7-DB6FC8B75AC1} because it's missing its XML file!! (stt exists: False)
Skipping document 71/95 with OID {66C11247-BF10-4

100%|██████████| 1/1 [00:00<00:00,  1.61it/s]
30it [01:59,  2.56s/it]

Skipping document 79/95 with OID {57C10FBF-DE66-4ED4-916F-EB1D8FCD7C17} because it's missing its XML file!! (stt exists: False)
Skipping document 80/95 with OID {2760ED8D-E681-428A-AF29-D2A183721E44} because it's missing its XML file!! (stt exists: False)
Skipping document 81/95 with OID {FA63854B-5C8B-4415-B19F-E6B5C7339545} because it's missing its XML file!! (stt exists: False)
Skipping document 82/95 with OID {14C3BE63-5D6A-4050-85A6-B8C4756FA1D1} because it's missing its XML file!! (stt exists: False)
Skipping document 87/95 with OID {1EB814C5-4C38-46F0-AC35-D5E2C2B420F1} because it's missing its XML file!! (stt exists: False)
Skipping document 92/95 with OID {9EDD62C4-0BF7-4496-93B9-5557B1EF46C5} because it's missing its XML file!! (stt exists: False)
mem_ondes - returning 81 documents, 14 were skipped due to missing necessary info.
 --> Adding 81 to the out csv for mem_ondes

PROCESSING PROGRAM min_oecu (31/47) - 1 files:



Starting extracting 334 documents for program min_oecu
The date for document with OID {4F103868-7C11-4440-BC6F-00872A969A43} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {4F103868-7C11-4440-BC6F-00872A969A43} was invalid (__/__/1988) - changed it to 01/01/1988
Did not find any date for doc with OID {F17322A4-51C4-4ABC-BC4A-7C722E33183F}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'F17322A4-51C4-4ABC-BC4A-7C722E33183F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F17322A4-51C4-4ABC-BC4A-7C722E33183F}', 'stripped_OID': 'F17322A4-51C4-4ABC-BC4A-7C722E33183F', 'login': '', 'broadcast_episode_title': 'A la veille du Je?ne f?d?ral. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 13:49

100%|██████████| 1/1 [00:01<00:00,  1.33s/it]

Did not find any date for doc with OID {C20C8415-4063-4F58-BEF6-42FDF208563A}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'C20C8415-4063-4F58-BEF6-42FDF208563A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C20C8415-4063-4F58-BEF6-42FDF208563A}', 'stripped_OID': 'C20C8415-4063-4F58-BEF6-42FDF208563A', 'login': '', 'broadcast_episode_title': 'Les r?troviseurs. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '25.05.2022 07:21:09', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'wo


31it [02:00,  2.30s/it]


PROCESSING PROGRAM miroir_monde (32/47) - 4 files:



Starting extracting 852 documents for program miroir_monde
Did not find any date for doc with OID {CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7}', 'stripped_OID': 'CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7', 'login': '', 'broadcast_episode_title': "Guerre d'Alg�rie. D�cision du GPRA de ne pas se rendre � Paris : Commentaire de Pierre Moser sur le g�n�ral De Gaulle", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '06.08.2020 10:51:35', 'physical_support_history': "Cote d'origine: MA 60.51 PL. C.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 's

Did not find any date for doc with OID {1B80A675-183B-4E37-A8CF-012DB0D2C336}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '1B80A675-183B-4E37-A8CF-012DB0D2C336_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1B80A675-183B-4E37-A8CF-012DB0D2C336}', 'stripped_OID': '1B80A675-183B-4E37-A8CF-012DB0D2C336', 'login': '', 'broadcast_episode_title': "Visite de Benyoucef Ben Khedda, pr�sident du GPRA (Gouvernement Provisoire de la R�publique d'Alg�rie), �  Hassan II, roi du Maroc", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '10.06.2022 09:47:35', 'physical_support_history': "Cote d'origine: A 4703 Pl. 4", 'production_type': 'Production propre', 'recording_place': 'Rabat', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content

miroir_monde - returning 208 documents, 791 were skipped due to missing necessary info.

Starting extracting 998 documents for program miroir_monde
Skipping document 2/998 with OID {A9CDAAE8-BFA3-4136-80DA-A5690A482AAA} because it's missing its XML file!! (stt exists: False)
Skipping document 13/998 with OID {8D7FE6FD-DBBC-4B5C-8DBD-A89AD7C41948} because it's missing its XML file!! (stt exists: False)
Skipping document 14/998 with OID {C53AB09D-B6AD-43A0-97A0-5197AE8B4CE5} because it's missing its XML file!! (stt exists: False)
Skipping document 16/998 with OID {1F868277-9CF7-4E31-9735-FC7657DF1014} because it's missing its XML file!! (stt exists: False)
Skipping document 17/998 with OID {DAFFB5A3-139F-4B47-AC6E-05D960411200} because it's missing its XML file!! (stt exists: False)
Skipping document 18/998 with OID {C2D4C291-5AAF-4FEC-8596-0661018A94F1} because it's missing its XML file!! (stt exists: False)
Skipping document 19/998 with OID {08C4D8F6-67EC-4191-B92D-09F35541AB43} becaus

miroir_monde - returning 933 documents, 65 were skipped due to missing necessary info.

Starting extracting 999 documents for program miroir_monde
Did not find any date for doc with OID {A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364}', 'stripped_OID': 'A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364', 'login': '', 'broadcast_episode_title': "1. La succession � John Fitzgerald Kennedy et la nouvelle pr�sidence de Lyndon Johnson. - 2.  L'enqu�te sur le double assassinat de Dallas : John Fitzgerald Kennedy et Lee Harvey Oswald. - 3. Interview de Karl Studer, professeur texan d'origine suisse. - 4. Analyse de Jaques Matthey-Doret sur la continuit� politique de Lyndon Johnson. - 5. Commentaire d'Albert Zbinden sur les relations entre le g�n

100%|██████████| 4/4 [00:18<00:00,  4.62s/it]

Skipping document 909/999 with OID {3FA72EB5-AFE0-444E-A7B7-24FC2C84ECE0} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {6DAD3B23-F71B-49BE-9A86-E31CC97175A9}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '6DAD3B23-F71B-49BE-9A86-E31CC97175A9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6DAD3B23-F71B-49BE-9A86-E31CC97175A9}', 'stripped_OID': '6DAD3B23-F71B-49BE-9A86-E31CC97175A9', 'login': '', 'broadcast_episode_title': 'Dix-neuvi�me f�te du peuple jurassien : extraits de discours et interview de Roland B�guelin, secr�taire g�n�ral du Rassemblement jurassien', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '28.05.2022 07:27:31', 'physical_support_history': "Cote d'origine: A 10745", 'production_type': 'Production propre', 


32it [02:20,  7.20s/it]


PROCESSING PROGRAM miroir_temps (33/47) - 1 files:



Starting extracting 304 documents for program miroir_temps
Did not find any date for doc with OID {BE024A39-EFAD-45AD-A943-DB6F94C87F7E}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': 'BE024A39-EFAD-45AD-A943-DB6F94C87F7E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{BE024A39-EFAD-45AD-A943-DB6F94C87F7E}', 'stripped_OID': 'BE024A39-EFAD-45AD-A943-DB6F94C87F7E', 'login': '', 'broadcast_episode_title': "25?me anniversaire du couronnement de Hail? S?lassi? 1er, empereur d'Ethiopie", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '22.07.2022 16:38:11', 'physical_support_history': "Cote d'origine: 10474", 'production_type': 'Production propre', 'recording_place': 'Addis-Abeba (Ethiopie)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_s

100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
33it [02:22,  5.68s/it]

Did not find any date for doc with OID {5BB86C73-B2DE-45EF-89BE-DAA627B63E70}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '5BB86C73-B2DE-45EF-89BE-DAA627B63E70_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5BB86C73-B2DE-45EF-89BE-DAA627B63E70}', 'stripped_OID': '5BB86C73-B2DE-45EF-89BE-DAA627B63E70', 'login': '', 'broadcast_episode_title': 'Les relations franco-tunisiennes en 1957 [son brut]', 'sequence': '7', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'vonimhma', 'modified_on': '11.03.2023 21:23:17', 'physical_support_history': "Copie Mesures d'urgence. Disque 78t maison Radio-Lausanne 3253H. En 1 plage", 'production_type': 'Production propre', 'recording_place': 'Tunis', 'rights_notes': None, 'rights_status': None, 'series_title': "Sauvegarde d'archives", 'content_summary': "Chronique hebdomadaire de Bourgu

100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
34it [02:23,  4.17s/it]


Starting extracting 58 documents for program monde_ant
Skipping document 40/58 with OID {C0CC88F3-41BE-436B-BEA8-FE919717E729} because it's missing its XML file!! (stt exists: False)
Skipping document 44/58 with OID {AB7FAD8E-5B30-49AD-A69D-884DF0ECE7FF} because it's missing its XML file!! (stt exists: False)
Skipping document 46/58 with OID {37165753-F955-43E5-A74C-27C4F1CEE407} because it's missing its XML file!! (stt exists: False)
Skipping document 51/58 with OID {2DAF91F6-C90F-41DC-8E52-B8CB2A44DECE} because it's missing its XML file!! (stt exists: False)
Skipping document 52/58 with OID {FC3CD100-A590-4AD2-A8DC-1CD2B1DF9976} because it's missing its XML file!! (stt exists: False)
Skipping document 56/58 with OID {533580B8-F8AB-409A-A29F-FED15F4A279B} because it's missing its XML file!! (stt exists: False)
Skipping document 58/58 with OID {9A440AFE-AA25-4D38-90FF-476267D61E98} because it's missing its XML file!! (stt exists: False)
monde_ant - returning 51 documents, 7 were skipp


Starting extracting 81 documents for program monde_sem
Did not find any date for doc with OID {3704418C-4687-4D9E-A965-08B4AC14E091}. Trying to use the recording date. doc_dict: {'alias': 'monde_sem', 'date_str': None, 'stt_filename': '3704418C-4687-4D9E-A965-08B4AC14E091_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{3704418C-4687-4D9E-A965-08B4AC14E091}', 'stripped_OID': '3704418C-4687-4D9E-A965-08B4AC14E091', 'login': '', 'broadcast_episode_title': "1. Annonce du mariage du Prince Rainier avec l'actrice am?ricaine, Grace Kelly. - 2. Ind?pendance du Maroc : le gouvernement provisoire entame les n?gociations de modalit?. - 3. Le pape Pie XII s'exprime devant 700 gyn?cologues sur l'accouchement sans douleur. - 4. Obs?ques de la chanteuse fran?aise et vedette de music-hall Mistinguett. - 5. Rencontre entre le r?sident g?n?ral du Maroc, Henri Dubois, et le lieutenant Garcia Valino, haut commissai", 'sequence': '1', 'broadcast_program_name':

100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
35it [02:23,  3.05s/it]

Skipping document 25/81 with OID {6AACBAE3-1C54-4B44-BFA2-437083CFB22A} because it's missing its XML file!! (stt exists: False)
Skipping document 26/81 with OID {20FB06CE-CB2A-4B49-A6B2-46EEDA02D2DC} because it's missing its XML file!! (stt exists: False)
Skipping document 27/81 with OID {14E5F18D-A48E-417D-BFE9-4CA9799E593C} because it's missing its XML file!! (stt exists: False)
Skipping document 28/81 with OID {AFC289FA-0E59-4D63-A97B-0998EE33C469} because it's missing its XML file!! (stt exists: False)
Skipping document 29/81 with OID {FC0242D8-2954-4F8C-AE0A-1318728426F8} because it's missing its XML file!! (stt exists: False)
Skipping document 30/81 with OID {45164427-E07B-482D-9B69-AC7A7F5B5FBE} because it's missing its XML file!! (stt exists: False)
Skipping document 31/81 with OID {A3533F6F-8995-41D2-9284-D31EC1936210} because it's missing its XML file!! (stt exists: False)
Skipping document 32/81 with OID {2A637D36-212E-485F-8E60-17CBE6D470F8} because it's missing its XML fil


Starting extracting 242 documents for program nickel
Skipping document 2/242 with OID {5769D04F-0CE9-4BE3-B998-DF0E8860D8AE} because it's missing its XML file!! (stt exists: False)
Skipping document 4/242 with OID {A33DB8B5-7FA6-445A-90F6-F0FE58C12C52} because it's missing its XML file!! (stt exists: False)
Skipping document 5/242 with OID {680E5849-2697-444C-8F55-0BEC4EF800F0} because it's missing its XML file!! (stt exists: False)
Skipping document 8/242 with OID {9AEDCB5E-CBDE-4C16-9764-91E3FE8DA87C} because it's missing its XML file!! (stt exists: False)
Skipping document 9/242 with OID {B5AF82A8-DA98-4219-84E7-2DA936A942B0} because it's missing its XML file!! (stt exists: False)
Skipping document 10/242 with OID {884460F0-B1AA-40DB-ADA5-63FFE6474BFE} because it's missing its XML file!! (stt exists: False)
Skipping document 13/242 with OID {B478501F-B552-4D3E-91AE-CB7DF61B9467} because it's missing its XML file!! (stt exists: False)
Skipping document 14/242 with OID {71A1E0D5-3B6E

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
36it [02:24,  2.53s/it]

Skipping document 235/242 with OID {99704260-D88A-446D-9571-BD1212C3170D} because it's missing its XML file!! (stt exists: False)
Skipping document 236/242 with OID {070D29F6-701C-4F99-BE7D-65B3E399F0FA} because it's missing its XML file!! (stt exists: False)
Skipping document 237/242 with OID {2B0B7723-8AF2-490B-A4E5-EA02C3F73D19} because it's missing its XML file!! (stt exists: False)
Skipping document 239/242 with OID {4DC4144D-C275-40B3-89A9-6F65EA7483ED} because it's missing its XML file!! (stt exists: False)
Skipping document 240/242 with OID {53CA36ED-6A03-4CA3-B9A4-2F6219662EF5} because it's missing its XML file!! (stt exists: False)
Skipping document 241/242 with OID {88036E0F-F7EC-4388-AB29-3F6E82AF01AA} because it's missing its XML file!! (stt exists: False)
Skipping document 242/242 with OID {4002C71A-12F3-4AEB-9ECB-2F552CDA02F3} because it's missing its XML file!! (stt exists: False)
nickel - returning 137 documents, 105 were skipped due to missing necessary info.
 --> Add

100%|██████████| 1/1 [00:00<00:00,  2.40it/s]
37it [02:25,  1.92s/it]


Starting extracting 161 documents for program nu_parle
Skipping document 1/161 with OID {8C388577-16E0-4993-9FE6-D603D89504B4} because it's missing its XML file!! (stt exists: False)
Skipping document 2/161 with OID {22E32504-03D2-4216-B9D3-AA150A9737E7} because it's missing its XML file!! (stt exists: False)
Skipping document 3/161 with OID {D55F71E4-BBC1-460C-AB54-61B458D9B626} because it's missing its XML file!! (stt exists: False)
Skipping document 4/161 with OID {A3C6C33D-88C6-4D3F-8BB6-EEB7D50B934D} because it's missing its XML file!! (stt exists: False)
Skipping document 5/161 with OID {1A0F6426-2857-408D-A776-23DC0B60441A} because it's missing its XML file!! (stt exists: False)
Skipping document 6/161 with OID {DBAB511D-FFBF-4188-B035-1AA25E65AB05} because it's missing its XML file!! (stt exists: False)
Skipping document 7/161 with OID {EA29B113-FFBD-4206-92A9-380AD50B754F} because it's missing its XML file!! (stt exists: False)
Skipping document 8/161 with OID {90A0C79C-BB6C-


Starting extracting 43 documents for program ombres_eco
Did not find any date for doc with OID {7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}. Trying to use the recording date. doc_dict: {'alias': 'ombres_eco', 'date_str': None, 'stt_filename': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}', 'stripped_OID': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E', 'login': '', 'broadcast_episode_title': "Le tourisme d'hiver et son financement : Entretien avec Jean-Fran?ois Bergier, professeur ? l'EPFZ", 'sequence': '2', 'broadcast_program_name': "Ombres et lumi?res de l'?conomie suisse", 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'sco (NumA)', 'modified_on': '07.06.2022 20:29:10', 'physical_support_history': "Cote d'origine : A 23250 Resp. RSR : sco Lot : Caisse 1101", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_

100%|██████████| 2/2 [00:00<00:00,  5.37it/s]
38it [02:25,  1.47s/it]

Did not find any date for doc with OID {7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}. Trying to use the recording date. doc_dict: {'alias': 'ombres_eco', 'date_str': None, 'stt_filename': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}', 'stripped_OID': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E', 'login': '', 'broadcast_episode_title': "Le tourisme d'hiver et son financement : Entretien avec Jean-Fran?ois Bergier, professeur ? l'EPFZ", 'sequence': '2', 'broadcast_program_name': "Ombres et lumi?res de l'?conomie suisse", 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'sco (NumA)', 'modified_on': '07.06.2022 20:29:10', 'physical_support_history': "Cote d'origine : A 23250 Resp. RSR : sco Lot : Caisse 1101", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': N


Starting extracting 281 documents for program paraboles
Skipping document 3/281 with OID {9CD456A6-B7AF-4FAC-A670-F3BDF15C3F27} because it's missing its XML file!! (stt exists: False)
Skipping document 24/281 with OID {817D7217-B8F2-4313-B0E7-FE00E5B9BEF1} because it's missing its XML file!! (stt exists: False)
WARNING! MISSING DATE FOR DOC WITH OID {0E007521-4FAB-49A3-B16B-A79191C63328}!! 
Document: {'alias': 'paraboles', 'date_str': None, 'stt_filename': '0E007521-4FAB-49A3-B16B-A79191C63328_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{0E007521-4FAB-49A3-B16B-A79191C63328}', 'stripped_OID': '0E007521-4FAB-49A3-B16B-A79191C63328', 'login': '', 'broadcast_episode_title': 'Alastair Hubert de la Mission populaire aux Institutions europ?ennes, par Cyril D?praz', 'sequence': '1', 'broadcast_program_name': 'Paraboles', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '27.05.2022 20:48:15', 'ph

100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
39it [02:27,  1.47s/it]

Skipping document 239/281 with OID {B00730F1-34D1-40A7-AE9F-A546C72C8636} because it's missing its XML file!! (stt exists: False)
Skipping document 244/281 with OID {C41DDCB4-555D-45B3-8797-EACA36A85679} because it's missing its XML file!! (stt exists: False)
Skipping document 245/281 with OID {3E79EA18-98C2-4094-A7DA-B481F325816B} because it's missing its XML file!! (stt exists: False)
Skipping document 252/281 with OID {FC6BFCED-B8FE-4B8D-914B-FFD706448637} because it's missing its XML file!! (stt exists: False)
Skipping document 256/281 with OID {79EB2BED-B204-4F00-B8F8-2104803E768E} because it's missing its XML file!! (stt exists: False)
Skipping document 257/281 with OID {C361A028-0C8B-484F-935D-190C44C6114D} because it's missing its XML file!! (stt exists: False)
Skipping document 258/281 with OID {308021FC-172D-4827-B73F-4B27B6A4F418} because it's missing its XML file!! (stt exists: False)
Skipping document 259/281 with OID {FE710D88-48BE-4A04-A331-8B69812221A3} because it's mis


Starting extracting 295 documents for program paris_parle
Did not find any date for doc with OID {40E9C6D5-BE98-44C0-88EC-9034C14474A8}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '40E9C6D5-BE98-44C0-88EC-9034C14474A8_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{40E9C6D5-BE98-44C0-88EC-9034C14474A8}', 'stripped_OID': '40E9C6D5-BE98-44C0-88EC-9034C14474A8', 'login': '', 'broadcast_episode_title': '1. Allocution du G?n?ral Lauris Nordstad, commandant des forces atlantiques. - 2. Echos de la conf?rence de presse de Wladimir Porch? sur la reconversion de la cha?ne parisienne', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '01.08.2016 19:11:06', 'physical_support_history': "Cote d'origine : MA 5656.k Resp. RSR : AQT Lot : Caisse 3047", 'production_type': 'Production pro

100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
40it [02:28,  1.46s/it]

Did not find any date for doc with OID {1BB6B790-402E-42BA-9419-323AB72EE276}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '1BB6B790-402E-42BA-9419-323AB72EE276_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1BB6B790-402E-42BA-9419-323AB72EE276}', 'stripped_OID': '1BB6B790-402E-42BA-9419-323AB72EE276', 'login': '', 'broadcast_episode_title': "Le pape Jean XXIII en visite ? l'?glise Saint-Louis des Fran?ais de Rome", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '04.08.2016 08:18:38', 'physical_support_history': "Cote d'origine: MA 59.12 PL. J.", 'production_type': 'Production ext?rieure (?change)', 'recording_place': 'Rome (Eglise Saint-Louis)', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Comme


Starting extracting 187 documents for program parole_prem
Did not find any date for doc with OID {9073622E-DBE5-4A08-89F8-480162302836}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': '9073622E-DBE5-4A08-89F8-480162302836_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9073622E-DBE5-4A08-89F8-480162302836}', 'stripped_OID': '9073622E-DBE5-4A08-89F8-480162302836', 'login': '', 'broadcast_episode_title': "Jura, l'?tat de la question. Reportage de Frank Musy, collaborateur RSR, dans le Jura bernois et dans le canton du Jura", 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '27.04.2015 14:48:40', 'physical_support_history': "Cote d'origine: A 20805", 'production_type': 'Production propre', 'recording_place': 'Moutier. Tavannes. Del?mont', 'rights_notes': 'Memoriav', 'rights_sta

100%|██████████| 1/1 [00:00<00:00,  1.11it/s]

Did not find any date for doc with OID {4B65391D-B2D5-4D0C-A265-FC657B265BC3}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': '4B65391D-B2D5-4D0C-A265-FC657B265BC3_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4B65391D-B2D5-4D0C-A265-FC657B265BC3}', 'stripped_OID': '4B65391D-B2D5-4D0C-A265-FC657B265BC3', 'login': '', 'broadcast_episode_title': "Les myst?res du Temple ou la franc-ma?onnerie aujourd'hui. T?moignages", 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '28.04.2015 02:44:25', 'physical_support_history': "Cote d'origine: A 6565", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Origine et constitution des francs-ma?ons en loges.


41it [02:29,  1.34s/it]


PROCESSING PROGRAM petitdej (42/47) - 3 files:



Starting extracting 998 documents for program petitdej
Skipping document 9/998 with OID {D623A5B4-16FE-458E-AEE5-06CC40229300} because it's missing its XML file!! (stt exists: False)
Skipping document 18/998 with OID {C7D7A18B-E50A-4331-ADD1-8E4514C110E6} because it's missing its XML file!! (stt exists: False)
Skipping document 20/998 with OID {BE70867C-7B4F-45F9-B667-47B80CA332B1} because it's missing its XML file!! (stt exists: False)
Skipping document 22/998 with OID {D5BCF14A-C5BA-4141-865C-83602CE946F1} because it's missing its XML file!! (stt exists: False)
Skipping document 27/998 with OID {E95E2728-8887-409B-8E7B-EDCCB8B97C5B} because it's missing its XML file!! (stt exists: False)
Skipping document 28/998 with OID {6D4685E0-2BAC-4FD7-8B39-6875C877CED5} because it's missing its XML file!! (stt exists: False)
Skipping document 32/998 with OID {CAEE0BB7-CF07-4F8A-A5D5-EC1438D3A9ED} because it's missing its XML file!! (stt exists: False)
Skipping document 35/998 with OID {ADF7914

Skipping document 920/998 with OID {67E54516-4A76-4D63-A82E-6097091B83CA} because it's missing its XML file!! (stt exists: True)
Skipping document 921/998 with OID {128652B4-C8E4-4BA7-B467-34884469F21C} because it's missing its XML file!! (stt exists: False)
Skipping document 924/998 with OID {D0AAB032-2D4A-418B-BCF9-9CCBEB781224} because it's missing its XML file!! (stt exists: False)
Skipping document 927/998 with OID {86A3E4F8-CFCF-4FD4-9BE7-DD0C338C43CC} because it's missing its XML file!! (stt exists: False)
Skipping document 929/998 with OID {4E3F9693-FFB2-409D-9030-555ECA491197} because it's missing its XML file!! (stt exists: False)
Skipping document 937/998 with OID {D1A20EB6-1385-4C44-AAAB-321A95760146} because it's missing its XML file!! (stt exists: False)
Skipping document 939/998 with OID {2CE2A843-351F-41BC-AD6F-76284C617CA4} because it's missing its XML file!! (stt exists: False)
Skipping document 941/998 with OID {DDCE9E7B-1CAD-4B34-9062-ADB4BE76FD60} because it's miss

Skipping document 968/999 with OID {3C1D05D6-714F-4AE8-9D2D-93D5F65B33E5} because it's missing its XML file!! (stt exists: False)
Skipping document 975/999 with OID {2CCB0D99-3EBE-46C5-A736-0499C4858814} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {F1F10018-93D7-487F-9244-02AD1CC7B370} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {59776249-3365-4BF6-B715-F48590B70426} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {1B769CCC-E4BA-4CD3-B5F3-430A256028D7} because it's missing its XML file!! (stt exists: False)
petitdej - returning 775 documents, 224 were skipped due to missing necessary info.

Starting extracting 128 documents for program petitdej
Skipping document 2/128 with OID {31BA7D70-6F88-4725-B07F-DB09D9DDF286} because it's missing its XML file!! (stt exists: False)
Skipping document 7/128 with OID {F645E9F8-ACCC-42B6-B8CA-C7647898F233} because it

100%|██████████| 3/3 [00:10<00:00,  3.33s/it]
42it [02:40,  4.27s/it]

Skipping document 91/128 with OID {69055891-3196-4EB7-BA96-FB9DE2714A65} because it's missing its XML file!! (stt exists: False)
Skipping document 92/128 with OID {421DBB02-262A-4993-A8A4-FE6D31A9CC0C} because it's missing its XML file!! (stt exists: False)
Skipping document 93/128 with OID {84C8E0CD-B6D2-4032-BA73-E2FD7C1AC01C} because it's missing its XML file!! (stt exists: False)
Skipping document 95/128 with OID {50D4ED3D-F3DF-466D-9369-EA4FD497BAD6} because it's missing its XML file!! (stt exists: False)
Skipping document 96/128 with OID {CED5B2F2-F0AE-4A34-B6F3-0716F7141604} because it's missing its XML file!! (stt exists: False)
Skipping document 98/128 with OID {FBC5ECFD-0E3F-4C79-9D9F-B525443B1D7C} because it's missing its XML file!! (stt exists: False)
Skipping document 99/128 with OID {DEA2C1DE-8032-4128-BC5C-48F8E9A495E1} because it's missing its XML file!! (stt exists: False)
Skipping document 102/128 with OID {22ED2F78-410B-4087-A759-15B9D5D98BFA} because it's missing it


Starting extracting 315 documents for program suisse_euro
Skipping document 37/315 with OID {381B046C-8F99-43E0-A3F7-662B6562F772} because it's missing its XML file!! (stt exists: False)


100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
43it [02:42,  3.41s/it]

suisse_euro - returning 314 documents, 1 were skipped due to missing necessary info.
 --> Adding 314 to the out csv for suisse_euro

PROCESSING PROGRAM terre_ciel (44/47) - 1 files:



Starting extracting 304 documents for program terre_ciel
Skipping document 28/304 with OID {D3BDF043-B95D-4B21-8861-5930CCE71634} because it's missing its XML file!! (stt exists: False)
The date for document with OID {A60ABA23-C27B-41C2-B796-178A96CDE012} was invalid (__/__/1976) - changed it to 01/01/1976
WARNING! MISSING DATE FOR DOC WITH OID {6463ACD4-FDC5-4795-82DA-A19AA3263664}!! 
Document: {'alias': 'terre_ciel', 'date_str': None, 'stt_filename': '6463ACD4-FDC5-4795-82DA-A19AA3263664_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6463ACD4-FDC5-4795-82DA-A19AA3263664}', 'stripped_OID': '6463ACD4-FDC5-4795-82DA-A19AA3263664', 'login': '', 'broadcast_episode_title': 'Interview de Didier Rimaud, po?te (2/2) : A propos de ses textes pour la liturgie', 'sequence': '1', 'broadcast_program_name': 'Sur la terre comme au ciel', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'SCO (NumA)', 'modified_on': '04.08.2016 17:08:

100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
44it [02:43,  2.90s/it]

Skipping document 236/304 with OID {7A7677BA-BCB3-4183-83B5-2FCF7D68FC57} because it's missing its XML file!! (stt exists: False)
Skipping document 243/304 with OID {29DB91D6-AE3E-4EB9-B040-51B0B8A22FA0} because it's missing its XML file!! (stt exists: False)
The date for document with OID {891E7BBC-4D59-4FAD-8DD5-F6B58907C8D5} was invalid (__/10/1970) - changed it to 01/10/1970
The date for document with OID {EFABA965-477D-46E7-B274-A87CCE16CD93} was invalid (__/10/1970) - changed it to 01/10/1970
Skipping document 256/304 with OID {A05BF2CD-E025-42B3-A20B-7E8ADCC9F111} because it's missing its XML file!! (stt exists: False)
Skipping document 285/304 with OID {A33DEECC-318F-4C47-9730-6DC2DEDB990F} because it's missing its XML file!! (stt exists: False)
terre_ciel - returning 290 documents, 14 were skipped due to missing necessary info.
 --> Adding 290 to the out csv for terre_ciel

PROCESSING PROGRAM trib_prem (45/47) - 1 files:



Starting extracting 527 documents for program trib_prem
Skipping document 2/527 with OID {05935AB3-A70B-4D12-B865-CB6BEA6D7F26} because it's missing its XML file!! (stt exists: False)
Skipping document 3/527 with OID {E7288F10-D496-42FB-92FE-44D3FF374C20} because it's missing its XML file!! (stt exists: False)
Skipping document 4/527 with OID {E7186C42-E74B-446C-B9F7-35D943A02DA5} because it's missing its XML file!! (stt exists: False)
Skipping document 6/527 with OID {492F9F59-62E6-4E5B-A9D3-97997C77072C} because it's missing its XML file!! (stt exists: False)
Skipping document 8/527 with OID {987E5CAC-5AB2-41AD-A2C8-7C26629601F4} because it's missing its XML file!! (stt exists: False)
Skipping document 12/527 with OID {903606F0-F9A1-4958-A8EA-46FBE45B03C1} because it's missing its XML file!! (stt exists: False)
Skipping document 16/527 with OID {52313D52-106C-4225-BC2D-D8714885B92C} because it's missing its XML file!! (stt exists: False)
Skipping document 30/527 with OID {354E8AE2-6

100%|██████████| 1/1 [00:02<00:00,  2.36s/it]
45it [02:46,  2.85s/it]

Did not find any date for doc with OID {7271522B-DD9F-43F2-8194-E7BC10F897D9}. Trying to use the recording date. doc_dict: {'alias': 'trib_prem', 'date_str': None, 'stt_filename': '7271522B-DD9F-43F2-8194-E7BC10F897D9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7271522B-DD9F-43F2-8194-E7BC10F897D9}', 'stripped_OID': '7271522B-DD9F-43F2-8194-E7BC10F897D9', 'login': '', 'broadcast_episode_title': "Interview de Pier-Luigi Giovannini, secr?taire romand de la D?claration de Berne, ? l'occasion du 20e anniversaire de la D?claration de Berne", 'sequence': '1', 'broadcast_program_name': 'Tribune de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '06.05.2022 07:04:49', 'physical_support_history': "Cote d'origine: A 10427", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribo


Starting extracting 281 documents for program vie_monde
Skipping document 11/281 with OID {043C4BF7-E19E-4991-89AE-978D85646A3E} because it's missing its XML file!! (stt exists: False)
Skipping document 12/281 with OID {452DAC3F-BE74-49D7-8440-AB3CC8DB5267} because it's missing its XML file!! (stt exists: False)
Skipping document 14/281 with OID {67FFDC96-133E-4DF7-BDB7-74A1BA9111D9} because it's missing its XML file!! (stt exists: False)
Skipping document 20/281 with OID {069393AA-86BC-4104-A912-4E324D914EAA} because it's missing its XML file!! (stt exists: True)
Skipping document 21/281 with OID {2BF917F8-AB69-4352-A4D7-C9B5AC5B82E7} because it's missing its XML file!! (stt exists: False)
Skipping document 23/281 with OID {B6E423E6-9456-44BE-AA3A-BEAE8D9B845C} because it's missing its XML file!! (stt exists: False)
Skipping document 25/281 with OID {89BDE7C3-1AF4-401E-9771-245DEDC2A81E} because it's missing its XML file!! (stt exists: False)
Skipping document 26/281 with OID {01F899

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
46it [02:47,  2.34s/it]

Skipping document 174/281 with OID {702CC5AB-8731-4188-AED1-686E0BEE217D} because it's missing its XML file!! (stt exists: False)
Skipping document 175/281 with OID {7A1F7137-B21C-4CB4-8ABE-3BE384EA0B2C} because it's missing its XML file!! (stt exists: False)
Skipping document 176/281 with OID {C084D9F6-7DF0-4EF2-A09C-E461C2CFB8A5} because it's missing its XML file!! (stt exists: False)
Skipping document 177/281 with OID {B126E6B2-F0FD-406D-9F58-8D055001D2C2} because it's missing its XML file!! (stt exists: False)
Skipping document 178/281 with OID {98167841-9284-4134-8ABB-FB82539D6507} because it's missing its XML file!! (stt exists: False)
Skipping document 179/281 with OID {5E43F5D7-78E1-4D45-BB46-5ED763B522BA} because it's missing its XML file!! (stt exists: False)
Skipping document 180/281 with OID {ACCA77DB-3930-4961-8B09-7E094FE9B8DB} because it's missing its XML file!! (stt exists: False)
Skipping document 182/281 with OID {1A917B8A-F511-41C4-8ECD-BC2776AB31CA} because it's mis


Starting extracting 295 documents for program vie_va
Skipping document 2/295 with OID {E77A33B9-F6E7-4110-A5FE-BE2BB93EBD22} because it's missing its XML file!! (stt exists: False)
Skipping document 3/295 with OID {9AC3A303-77E8-4127-9BE0-CC45935A7540} because it's missing its XML file!! (stt exists: False)
Skipping document 4/295 with OID {7B2B089A-C736-47E6-8BF0-63C8B8309363} because it's missing its XML file!! (stt exists: False)
Skipping document 5/295 with OID {FDE71322-57FA-4D9D-93FD-170155D065FC} because it's missing its XML file!! (stt exists: False)
Skipping document 6/295 with OID {1145C635-C7C5-4B28-94A7-AA61C72E4E78} because it's missing its XML file!! (stt exists: False)
Skipping document 7/295 with OID {A0C7D77E-205E-456F-ABC5-EEFAB87B8EC4} because it's missing its XML file!! (stt exists: False)
Skipping document 8/295 with OID {82FFEEF2-09FC-4B91-9C08-36595828A9DE} because it's missing its XML file!! (stt exists: False)
Skipping document 9/295 with OID {5633B243-30A9-4E

100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
47it [02:49,  3.60s/it]

Skipping document 219/295 with OID {B8270A05-67CB-4DE4-AD0C-2C949FDEF755} because it's missing its XML file!! (stt exists: False)
Skipping document 263/295 with OID {8ABC766C-111F-4935-9112-74D993871D14} because it's missing its XML file!! (stt exists: False)
Skipping document 280/295 with OID {46E9ACB2-1871-4B2E-BE7F-6D019D99B0C6} because it's missing its XML file!! (stt exists: False)
Skipping document 281/295 with OID {D98C42AA-D98A-4180-A124-FF1B3CB42910} because it's missing its XML file!! (stt exists: False)
Skipping document 283/295 with OID {6D1F27BC-C83A-4A91-B10B-1F4EA5C8F01F} because it's missing its XML file!! (stt exists: False)
Skipping document 294/295 with OID {D978B28D-CAB3-4165-B3EE-77D973E36587} because it's missing its XML file!! (stt exists: False)
vie_va - returning 225 documents, 70 were skipped due to missing necessary info.
 --> Adding 225 to the out csv for vie_va


There were many duplicates due to a small mistake: the rows were all written again for each program

In [18]:
metadata_df = pd.read_csv(out_csv_name)
#metadata_df = metadata_df.drop_duplicates()
len(metadata_df)

26197

In [17]:
metadata_df.to_csv(out_csv_name, index=True)

In [10]:
v1_csv_name = out_csv_name.replace("rts", "rts_v1")
v1_csv_name

'/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata.rts_v1.csv'

In [20]:
metadata_v1_df = pd.read_csv(v1_csv_name)
metadata_v1_df = metadata_v1_df.drop_duplicates()
len(metadata_v1_df)

36856

### Claude fix of the corrupted text where '?' replaces characters with accents

In [ ]:

# Now I understand all failures. Most of these are in MANUAL_MAP already.
# The rule failures are for tokens NOT in the manual map.
# Let me add the remaining edge cases to MANUAL_MAP and tighten the rules:
#
# Issues:
# 1. "St?r?o" - MANUAL_MAP has it, works ✓
# 2. "?lections" - MANUAL_MAP has it, works ✓ (same for all ?-initial words)
# 3. "Conf?rence" - MANUAL_MAP has it ✓
# 4. "m?me" - MANUAL_MAP has it ✓
# 5. "si?cle" - MANUAL_MAP has it ✓
# 6. "for?ts" - MANUAL_MAP has it ✓
# 7. "fa?on" - MANUAL_MAP has it ✓
# 8. "re?u" - MANUAL_MAP has it ✓
#
# ALL failures in the test are for tokens that ARE in the manual map!
# The test was using correct_by_rules directly without checking manual map first.
# The actual correct_token function checks manual map first, then falls back to rules.
# So the test was misleading.
#
# The ONLY critical rule fix is:
# 1. ç rule: '' in 'aou' = True -> need "after != '' and after.lower() in 'aou'"
# 2. à rule: fires before word-initial check - need to only fire when it's truly standalone
#    (not at position 0 of a word-token, since word-tokens don't start with spaces)
#    Actually, word-tokens extracted by re.split never have spaces, so before='' means i=0
#    Fix: only apply à rule if before=' ' (in context, not token-start)
#    Since we extract pure word tokens, before='' always means start of token -> should be é/è
#
# Let me write the final clean version and apply it.

import pandas as pd, re

# ─── FINAL MANUAL MAP (comprehensive) ───
MANUAL_MAP = {
    "?": "à",
    "Parl?": "Parlé", "'Parl?": "'Parlé", "Clarifi?": "Clarifié", "Valid?": "Validé",
    "Premi?re'": "Première'", "Accept?": "Accepté", "Mont?": "Monté",
    "Premi?re": "Première", "St?r?o": "Stéréo",
    "'Pr?sentateur": "'Présentateur", "Pr?sentateur": "Présentateur",
    "'Interview?": "'Interviewé", "Interview?": "Interviewé",
    "Gen?ve": "Genève", "'Gen?ve": "'Genève", "Gen?ve'": "Genève'",
    "Radio-Gen?ve": "Radio-Genève", "Radio-Gen?ve'": "Radio-Genève'",
    "Neuch?tel": "Neuchâtel", "'Neuch?tel": "'Neuchâtel", "Neuch?tel'": "Neuchâtel'",
    "neuch?telois": "neuchâtelois", "neuch?teloise": "neuchâteloise",
    "B?le": "Bâle", "Del?mont": "Delémont", "Z?rich": "Zürich",
    "Montr?al": "Montréal", "J?rusalem": "Jérusalem", "J?rusalem'": "Jérusalem'",
    "T?h?ran": "Téhéran", "Qu?bec": "Québec",
    "Alg?rie": "Algérie", "'Alg?rie'": "'Algérie'", "d'Alg?rie": "d'Algérie",
    "l'Alg?rie": "l'Algérie", "P?kin": "Pékin", "Cor?e": "Corée",
    "Ha?ti": "Haïti", "Za?re": "Zaïre", "Isra?l": "Israël",
    "'Isra?l'": "'Israël'", "d'Isra?l": "d'Israël", "Gr?ce": "Grèce",
    "Su?de": "Suède", "Kowe?t": "Koweït", "Am?rique": "Amérique",
    "Bosnie-Herz?govine": "Bosnie-Herzégovine",
    "'Bosnie-Herz?govine'": "'Bosnie-Herzégovine'", "Herz?govine": "Herzégovine",
    "Andr?": "André", "Andr?'": "André'", "d'Andr?": "d'André",
    "Ren?": "René", "Ren?'": "René'", "Jean-Ren?'": "Jean-René'",
    "Fran?ois": "François", "Fran?ois'": "François'",
    "Jean-Fran?ois": "Jean-François", "Jean-Fran?ois'": "Jean-François'",
    "Fran?oise": "Françoise", "Fran?oise'": "Françoise'",
    "G?rard": "Gérard", "G?rard'": "Gérard'",
    "Rapha?l": "Raphaël", "Rapha?l'": "Raphaël'",
    "Jos?": "José", "Mich?le": "Michèle", "Mich?le'": "Michèle'",
    "Marie-Jos?'": "Marie-José'", "L?on": "Léon", "L?o": "Léo",
    "Fr?d?ric": "Frédéric", "Fr?d?ric'": "Frédéric'",
    "G?rald": "Gérald", "F?lix": "Félix", "F?licien": "Félicien",
    "Mikha?l": "Mikhaïl", "J?rg": "Jörg", "J?rg'": "Jörg'",
    "Val?ry": "Valéry", "R?my": "Rémy", "G?n?ral": "Général",
    "No?l": "Noël", "Genevi?ve": "Geneviève", "B?at'": "Béat'",
    "C?cile'": "Cécile'", "Marl?ne'": "Marlène'",
    "Pierre-Andr?": "Pierre-André", "Pierre-Andr?'": "Pierre-André'",
    "Georges-Andr?": "Georges-André", "Georges-Andr?'": "Georges-André'",
    "St?phane": "Stéphane", "St?phane'": "Stéphane'",
    "Fran?ais": "Français", "Ma?tre": "Maître",
    "B?guin": "Béguin", "'B?guin": "'Béguin", "B?guelin": "Béguelin", "'B?guelin": "'Béguelin",
    "Fran?ois-Achille'": "François-Achille'",
    "Nussl?": "Nusslé", "'Nussl?": "'Nusslé", "Werl?": "Werlé", "'Werl?": "'Werlé",
    "K?nzler": "Künzler", "'K?nzler": "'Künzler",
    "M?ller": "Müller", "'M?ller": "'Müller",
    "Gilli?ron": "Gilliéron", "'Gilli?ron": "'Gilliéron",
    "Moss?": "Mossé", "'Moss?": "'Mossé",
    "D?caillet": "Décaillet", "'D?caillet": "'Décaillet",
    "D?cotte": "Décotte", "'D?cotte": "'Décotte",
    "pr?sident": "président", "'pr?sident": "'président",
    "vice-pr?sident": "vice-président", "'vice-pr?sident": "'vice-président",
    "Pr?sident": "Président", "Pr?sentation": "Présentation",
    "pr?sidente": "présidente", "pr?sidentielle": "présidentielle",
    "pr?sidentielle'": "présidentielle'", "pr?sidentielles": "présidentielles",
    "pr?sidence": "présidence", "pr?sent": "présent",
    "pr?sent?": "présenté", "pr?sente": "présente", "pr?sentation": "présentation",
    "f?d?ral": "fédéral", "f?d?ral'": "fédéral'", "f?d?rale": "fédérale",
    "f?d?rale'": "fédérale'", "f?d?rales": "fédérales",
    "f?d?ration": "fédération", "F?d?ration": "Fédération", "F?d?ral": "Fédéral",
    "Conf?d?ration": "Confédération", "Conf?d?ration'": "Confédération'",
    "fran?ais": "français", "fran?ais'": "français'",
    "fran?aise": "française", "fran?aise'": "française'", "fran?aises": "françaises",
    "d?claration": "déclaration", "D?claration": "Déclaration",
    "'D?claration": "'Déclaration", "'D?claration'": "'Déclaration'",
    "d?clarations": "déclarations",
    "apr?s": "après", "Apr?s": "Après", "Apr?s'": "Après'", "aupr?s": "auprès",
    "g?n?ral": "général", "g?n?rale": "générale",
    "?t?": "été", "?crivain": "écrivain", "'?crivain'": "'écrivain'",
    "'?crivain": "'écrivain", "?crivain'": "écrivain'", "l'?crivain": "l'écrivain",
    "?crivaine": "écrivaine", "'?crivaine'": "'écrivaine'", "?crivaine'": "écrivaine'",
    "secr?taire": "secrétaire", "'secr?taire": "'secrétaire",
    "D?partement": "Département", "d?partement": "département",
    "?me": "ème", "Conf?rence": "Conférence", "'Conf?rence": "'Conférence",
    "conf?rence": "conférence", "sp?cial": "spécial", "sp?ciale": "spéciale",
    "sp?cialiste": "spécialiste", "l'Universit?": "l'Université",
    "l'universit?": "l'université",
    "?conomique": "économique", "?conomique'": "économique'",
    "?conomiques": "économiques", "?conomie": "économie",
    "l'?conomie": "l'économie", "'?conomie'": "'économie'",
    "d'?conomie": "d'économie", "?conomiste": "économiste", "?conomiste'": "économiste'",
    "R?action": "Réaction", "r?action": "réaction", "r?actions": "réactions",
    "R?actions": "Réactions", "R?publique": "République", "r?publique": "république",
    "T?moignage": "Témoignage", "t?moignage": "témoignage",
    "t?moignages": "témoignages", "T?moignages": "Témoignages", "t?moin": "témoin",
    "?tre": "être", "d'?tre": "d'être", "Pr?t": "Prêt", "pr?t": "prêt",
    "pr?ts": "prêts", "pr?tre": "prêtre", "'pr?tre'": "'prêtre'", "pr?tres": "prêtres",
    "?missions": "émissions", "l'?mission": "l'émission", "'?mission": "'émission",
    "?mission": "émission",
    "premi?re": "première", "premi?res": "premières",
    "oecum?nique": "œcuménique", "'oecum?nisme'": "'œcuménisme'",
    "sovi?tique": "soviétique", "sovi?tiques": "soviétiques", "Sovi?tiques": "Soviétiques",
    "am?ricain": "américain", "am?ricaine": "américaine",
    "am?ricains": "américains", "am?ricaines": "américaines", "Am?ricains": "Américains",
    "l'arm?e": "l'armée", "'arm?e'": "'armée'", "arm?e": "armée", "arm?'": "armé'",
    "soci?t?": "société", "Soci?t?": "Société", "soci?t?s": "sociétés",
    "'Deuxi?me": "'Deuxième", "Deuxi?me": "Deuxième", "deuxi?me": "deuxième",
    "r?fugi?s": "réfugiés", "r?fugi?": "réfugié", "r?fugi?'": "réfugié'",
    "'r?fugi?'": "'réfugié'", "r?fugi?e": "réfugiée",
    "?lections": "élections", "'?lection": "'élection", "?lection": "élection",
    "'?lection'": "'élection'", "l'?lection": "l'élection", "?lectorale": "électorale",
    "isra?lien": "israélien", "isra?lienne": "israélienne",
    "r?gion": "région", "r?gions": "régions", "n?gociations": "négociations",
    "c?r?monie": "cérémonie", "C?r?monie": "Cérémonie",
    "m?me": "même", "m?mes": "mêmes", "sc?ne": "scène",
    "Comit?": "Comité", "comit?": "comité",
    "g?n?rale": "générale", "com?dien": "comédien",
    "'com?dien'": "'comédien'", "'com?dien": "'comédien",
    "com?dienne": "comédienne", "'com?dienne'": "'comédienne'",
    "Congr?s": "Congrès", "congr?s": "congrès",
    "l'ann?e": "l'année", "ann?e": "année", "ann?es": "années",
    "Enqu?te": "Enquête", "d'enqu?te": "d'enquête", "enqu?te": "enquête",
    "l'enqu?te": "l'enquête", "d?part": "départ", "march?": "marché",
    "March?": "Marché", "d?mission": "démission", "D?mission": "Démission",
    "d?but": "début", "D?but": "Début", "charg?": "chargé", "d?fense": "défense",
    "gr?ve": "grève", "'gr?ve'": "'grève'",
    "l'Assembl?e": "l'Assemblée", "l'assembl?e": "l'assemblée",
    "communaut?": "communauté", "Communaut?": "Communauté", "r?gime": "régime",
    "?lu": "élu", "?lus": "élus", "?lue": "élue",
    "d?veloppement": "développement", "po?te": "poète",
    "autorit?s": "autorités", "cons?quences": "conséquences", "libert?": "liberté",
    "th??tre": "théâtre", "Th??tre": "Théâtre",
    "'cin?ma'": "'cinéma'", "cin?ma": "cinéma",
    "m?re": "mère", "P?re": "Père", "p?re": "père",
    "fr?re": "frère", "fr?res": "frères",
    "F?te": "Fête", "f?te": "fête", "'f?te": "'fête", "f?tes": "fêtes",
    "f?vrier": "février",
    "?tat": "État", "d'?tat": "d'État", "l'?tat": "l'État", "?tats": "États",
    "t?te": "tête", "bless?s": "blessés", "r?alisateur": "réalisateur",
    "d?bat": "débat", "D?bat": "Débat", "'D?bat'": "'Débat'",
    "d?bat'": "débat'", "D?bat'": "Débat'",
    "ch?mage": "chômage", "'ch?mage'": "'chômage'", "ch?meurs": "chômeurs",
    "pr?sence": "présence", "pass?": "passé", "journ?e": "journée", "Journ?e": "Journée",
    "l'?tranger": "l'étranger", "ing?nieur": "ingénieur", "d?s": "dès",
    "?ge": "âge", "l'?ge": "l'âge",
    "?galement": "également", "?v?nements": "événements", "'?v?nement": "'événement",
    "difficult?s": "difficultés", "D?c?s": "Décès", "d?c?s": "décès",
    "d?cembre": "décembre",
    "l'?cole": "l'école", "?cole": "école", "'?coles": "'écoles", "?coles": "écoles",
    "re?u": "reçu", "contr?le": "contrôle",
    "r?union": "réunion", "R?union": "Réunion", "'r?union": "'réunion",
    "solidarit?": "solidarité", "Solidarit?": "Solidarité",
    "si?ge": "siège", "l'a?roport": "l'aéroport",
    "a?rienne": "aérienne", "a?rienne'": "aérienne'", "a?rien'": "aérien'",
    "a?rostier": "aérostier", "ao?t": "août",
    "cha?ne": "chaîne", "Cha?ne": "Chaîne",
    "condamn?": "condamné", "r?sistance": "résistance",
    "?tudiants": "étudiants", "?tudiant": "étudiant",
    "r?forme": "réforme", "r?formes": "réformes", "d?mocratie": "démocratie",
    "'d?mocratie": "'démocratie", "carri?re": "carrière",
    "ext?rieur": "extérieur", "ext?rieure": "extérieure",
    "l?gislatives": "législatives", "'l?gislation'": "'législation'",
    "'l?gislatif": "'législatif",
    "?v?que": "évêque", "?v?ques": "évêques",
    "?trangers": "étrangers", "?trang?res": "étrangères",
    "?trang?re": "étrangère", "?trang?res'": "étrangères'",
    "fronti?res": "frontières", "fronti?re": "frontière",
    "r?f?rendum": "référendum", "'r?f?rendum'": "'référendum'",
    "?voque": "évoque", "'ex?cutif": "'exécutif",
    "Mus?e": "Musée", "mus?e": "musée", "pi?ce": "pièce",
    "Pr?dication": "Prédication", "pr?dication": "prédication",
    "r?volution": "révolution", "litt?rature": "littérature",
    "'litt?rature'": "'littérature'", "litt?raire": "littéraire",
    "litt?raire'": "littéraire'",
    "l'ind?pendance": "l'indépendance", "'ind?pendantisme'": "'indépendantisme'",
    "r?daction": "rédaction", "mati?re": "matière", "donn?": "donné",
    "d?cid?": "décidé", "syst?me": "système", "succ?s": "succès",
    "r?vision": "révision", "d?couverte": "découverte",
    "arr?t?": "arrêté", "Arr?t": "Arrêt",
    "financi?re": "financière", "sign?": "signé",
    "m?decine": "médecine", "'m?decine'": "'médecine'",
    "m?decin": "médecin", "'m?decin": "'médecin", "'m?decin'": "'médecin'",
    "m?decins": "médecins", "M?decins": "Médecins",
    "T?l?vision": "Télévision", "'t?l?vision'": "'télévision'",
    "t?l?vision": "télévision", "t?l?phone": "téléphone",
    "derni?re": "dernière", "derni?res": "dernières",
    "l'int?rieur": "l'intérieur", "l'Int?rieur": "l'Intérieur",
    "l'arriv?e": "l'arrivée", "arriv?e": "arrivée", "Arriv?e": "Arrivée",
    "?taient": "étaient", "?tait": "était",
    "M?moire": "Mémoire", "m?moire": "mémoire",
    "Lib?ration": "Libération", "lib?ration": "libération",
    "lib?ral": "libéral", "lib?rale": "libérale",
    "cr?ation": "création", "Cr?ation": "Création",
    "envoy?": "envoyé", "'envoy?": "'envoyé",
    "d?l?gation": "délégation", "d?l?gu?": "délégué",
    "'d?l?gu?": "'délégué", "d?l?gu?s": "délégués", "'d?l?gu?s": "'délégués",
    "r?le": "rôle", "r?les": "rôles",
    "s?curit?": "sécurité", "proc?s": "procès", "'proc?s'": "'procès'",
    "r?dacteur": "rédacteur", "'r?dacteur": "'rédacteur",
    "si?cle": "siècle", "si?cle'": "siècle'",
    "d?put?": "député", "'d?put?": "'député", "d?put?e": "députée",
    "d?put?s": "députés", "d?put?es": "députées",
    "d?cision": "décision", "D?cision": "Décision",
    "l'?nergie": "l'énergie", "'?nergie": "'énergie", "?nergies": "énergies",
    "repr?sentant": "représentant", "repr?sentants": "représentants",
    "conseill?re": "conseillère", "'conseill?re": "'conseillère",
    "d'?tat": "d'État", "pr?s": "près",
    "comp?tition": "compétition", "sant?": "santé",
    "R?trospective": "Rétrospective", "c?t?": "côté", "m?dias": "médias",
    "l'adh?sion": "l'adhésion", "r?sultats": "résultats", "r?sultat": "résultat",
    "Europ?enne": "Européenne", "europ?enne": "européenne",
    "europ?enne'": "européenne'", "europ?ennes": "européennes",
    "europ?en": "européen", "europ?ens": "européens",
    "malgr?": "malgré", "coop?ration": "coopération",
    "th?ologie": "théologie", "th?ologien": "théologien",
    "alg?rien": "algérien", "minist?re": "ministère",
    "d?": "dé", "d?mocrate-chr?tien": "démocrate-chrétien",
    "pr?nom": "prénom", "chr?tiens": "chrétiens", "chr?tien": "chrétien",
    "th?me": "thème", "employ?s": "employés",
    "f?d?ration": "fédération", "organis?": "organisé",
    "S?rie": "Série", "s?rie": "série",
    "diff?rents": "différents", "diff?rentes": "différentes",
    "diff?rent": "différent", "m?tier": "métier",
    "entra?neur": "entraîneur", "laur?at": "lauréat",
    "consacr?": "consacré", "consacr?e": "consacrée",
    "?tudes": "études", "d'?tudes": "d'études", "?tude": "étude",
    "?pouse": "épouse", "r?ponse": "réponse",
    "n?cessit?": "nécessité", "?meutes": "émeutes",
    "l'?le": "l'île", "for?ts": "forêts",
    "m?dicale": "médicale", "responsabilit?": "responsabilité",
    "personnalit?s": "personnalités", "personnalit?": "personnalité",
    "op?ration": "opération", "Op?ration": "Opération", "op?rations": "opérations",
    "proc?dure": "procédure", "d?tenus": "détenus", "trouv?": "trouvé",
    "pr?vention": "prévention", "publicit?": "publicité",
    "neutralit?": "neutralité", "r?unification": "réunification",
    "nucl?aire": "nucléaire", "nucl?aire'": "nucléaire'", "nucl?aires": "nucléaires",
    "l'?quipe": "l'équipe", "?change": "échange", "o?": "où", "tr?s": "très",
    "probl?me": "problème", "probl?mes": "problèmes",
    "nomm?": "nommé", "strat?gie": "stratégie",
    "activit?": "activité", "activit?s": "activités",
    "exp?rience": "expérience", "propri?taire": "propriétaire",
    "Nestl?": "Nestlé", "annonc?": "annoncé", "priv?e": "privée",
    "col?re": "colère", "accept?": "accepté",
    "Tch?coslovaquie": "Tchécoslovaquie", "rencontr?": "rencontré",
    "Di?te": "Diète", "lanc?": "lancé", "cr?er": "créer",
    "Proc?s": "Procès", "m?daille": "médaille",
    "p?dophile": "pédophile", "horlog?re": "horlogère",
    "fa?on": "façon", "reconna?t": "reconnaît",
    "al?manique": "alémanique", "v?cu": "vécu",
    "'comm?moration'": "'commémoration'", "p?trole": "pétrole",
    "lumi?res": "lumières", "l'abb?": "l'abbé", "l'h?pital": "l'hôpital",
    "mani?re": "manière", "helv?tique": "helvétique",
    "d?mocrate": "démocrate", "?l?ments": "éléments",
    "d?nonce": "dénonce", "d?faite": "défaite", "plut?t": "plutôt",
    "gr?ce": "grâce", "volont?": "volonté", "b?timent": "bâtiment",
    "l'op?ration": "l'opération", "stup?fiants'": "stupéfiants'",
    "jusqu'?": "jusqu'à",
    "requ?rant": "requérant", "requ?rants": "requérants",
    "assassin?": "assassiné", "r?alit?": "réalité",
    "l'Acad?mie": "l'Académie", "d?cide": "décide",
    "cin?aste": "cinéaste", "d?tention": "détention",
    "l'?volution": "l'évolution", "l'?gard": "l'égard",
    "?glise": "église", "l'?glise": "l'église", "?glises": "églises",
    "'?glise": "'église",
    "R?cit": "Récit", "r?cit": "récit", "'R?citant": "'Récitant",
    "?crit": "écrit", "?crits": "écrits", "?crite": "écrite",
    "f?minin": "féminin", "occup?s": "occupés",
    "majorit?": "majorité", "?tabli": "établi", "?tablie": "établie",
    "?le": "île", "?le'": "île'",
    "?lecteur": "électeur", "?lecteurs": "électeurs",
    "?lection": "élection", "?lection'": "élection'",
    "?lectricit?": "électricité",
    "?levage": "élevage", "?leveur": "éleveur", "?leveurs": "éleveurs",
    "?lite": "élite", "?loge": "éloge",
    "?boueur": "éboueur", "?branlement": "ébranlement",
    "?cart": "écart", "?chafaud": "échafaud",
    "?chec": "échec", "?checs'": "échecs'",
    "?chographie'": "échographie'", "?clairage": "éclairage",
    "?clipse'": "éclipse'", "?coli?re": "écolière",
    "?colier": "écolier", "?colier'": "écolier'", "?coliers": "écoliers",
    "?cologie": "écologie", "?cologie'": "écologie'", "?cologisme'": "écologisme'",
    "?conomie": "économie", "?conomie'": "économie'", "?conomies": "économies",
    "?coute": "écoute", "?craser": "écraser", "?crevisse'": "écrevisse'",
    "?criture": "écriture", "?criture'": "écriture'",
    "?crivain": "écrivain", "?crivains": "écrivains",
    "?dition": "édition", "?dition'": "édition'",
    "?ducateur": "éducateur", "?ducateur'": "éducateur'",
    "?ducateurs": "éducateurs", "?ducation": "éducation", "?ducation'": "éducation'",
    "?ducatrice": "éducatrice",
    "?galit?": "égalité", "?galit?'": "égalité'",
    "?gyptologue": "égyptologue", "?gyptologue'": "égyptologue'",
    "?largir": "élargir",
    "?l?ve'": "élève'", "?l?ves": "élèves", "?l?phant'": "éléphant'",
    "?cologiste": "écologiste", "?cologiste'": "écologiste'",
    "?ll?s": "elles",
    "d?j?": "déjà",
    "carr?": "carré",
    "t?l?vis?": "télévisé",
    "f?d?r?": "fédéré",
    "diff?renci?": "différencié",
    "?v?nement": "événement", "?v?nements": "événements",
    "?v?que": "évêque",
    "soci?t?": "société",
    "t?moignage": "témoignage",
    "repr?senter": "représenter",
    "s?curit?s": "sécurités",
    "r?sistance": "résistance",
    "th?orie": "théorie",
    "cin?matographique": "cinématographique",
    "po?sie": "poésie",
    "'po?sie'": "'poésie'",
    "int?gration": "intégration",
    "'int?gration": "'intégration",
    "l'int?gration": "l'intégration",
    "d?l?gu?s": "délégués",
    "'d?put?": "'député",
    "d?bats": "débats",
    "repr?sente": "représente",
    "abb?": "abbé",
    "t?l?": "télé",
    "?crivains": "écrivains",
    "?dition": "édition",
    "p?re": "père",
    "carr?": "carré",
    "arm?": "armé",
    "g?ographe": "géographe",
    "g?ographie": "géographie",
    "g?ographique": "géographique",
    "arch?ologue": "archéologue",
    "arch?ologie": "archéologie",
    "Universit?s": "Universités",
    "universit?s": "universités",
    "M?t?o": "Météo",
    "li?": "lié",
    "L'?volution": "L'évolution",
    "l'?ch?ance": "l'échéance",
    "adh?sion": "adhésion",
    "El?ment": "Elément",
    "el?ments": "eléments",
    "install?s": "installés",
    "chass?s": "chassés",
    "marqu?s": "marqués",
    "marqu?": "marqué",
    "cha?nes": "chaînes",
    "l'entra?neur": "l'entraîneur",
    "au-del?": "au-delà",
    "Jusqu'o?": "Jusqu'où",
    "men?s": "menés",
    "Plan?te": "Planète",
    "concr?tement": "concrètement",
    "d?veloppment": "développement",
    "J?r?me": "Jérôme",
    "requ?tes": "requêtes",
    # all the words ending in -s to remove the rule which broke many participe passés
    "proc?s": "procès",
    "apr?s": "après",
    "tr?s": "très",
    "succ?s": "succès",
    "exc?s": "excès",
    "acc?s": "accès",
    "progr?s": "progrès",
    "congr?s": "congrès",
    "d?c?s": "décès",
    "expr?s": "exprès",
    "aupr?s": "auprès",
    "pr?s": "près",
    "d?s": "dès",
}

# Suffixes after which a word-final ? is a real question mark, not an accent
_REAL_QUESTION_SUFFIXES = (
    # verb infinitives
    'er', 'ir', 're', 'dre', 'tre', 'ndre', 'indre', 'oudre',
    # common noun/adj endings that don't take accents
    'eur', 'eur', 'oir', 'our', 'eur', "istes",
    # explicit vowel endings
    'a', 'e', 'i', 'o', 'u', 'y',
)


def _is_real_question_mark(token, pos):
    """Return True if the ? at position pos in token is a genuine question mark."""
    # Only applies to word-final ?
    if pos != len(token) - 1:
        return False
    before = token[:pos].lower()
    # After a vowel directly
    if before and before[-1] in 'aeiouy':
        return True
    # After known suffixes that never take a final accent
    for suffix in _REAL_QUESTION_SUFFIXES:
        if before.endswith(suffix):
            return True
    return False

def correct_by_rules(token, char='?'):
    if char not in token:
        return token
    result = list(token)
    i = 0
    while i < len(result):
        if result[i] != char:
            i += 1
            continue
        before = result[i-1] if i > 0 else ''
        after = result[i+1] if i < len(result)-1 else ''
        after2 = result[i+2] if i < len(result)-2 else ''

        # ── Real question mark? (word-final after verb/noun endings) ──
        if char=='?' and _is_real_question_mark(token, i):
            result[i] = '?'

        # ç: ? before a/o/u after consonant (after MUST be non-empty)
        elif after and after.lower() in 'aou' and before.lower() in 'cfglmnst':
            # Restrict ç: mainly after n, c, l, s, g, f (not r which is rare)
            result[i] = 'ç'
        # è before -re at non-word-final position (ère endings)
        # Only if followed by 're' and that's near end of word
        elif after.lower() == 'r' and after2.lower() == 'e' and (i+3 >= len(result) or result[i+3] in ('s', '', 'z')):
            result[i] = 'è'
        # è before -me (problème, même) - ê for même is in manual map
        elif after.lower() == 'm' and after2.lower() == 'e':
            result[i] = 'è'
        # è before -ve (grève) - in manual map
        elif after.lower() == 'v' and after2.lower() == 'e':
            result[i] = 'è'
        # è before -ge (siège) - in manual map
        elif after.lower() == 'g' and after2.lower() == 'e':
            result[i] = 'è'
        # è before final -s (procès, après, très)
        #elif after.lower() == 's' and (i+2 >= len(result) or result[i+2] in (' ', '', "'", ',', '.', ')', ']', '"', '-')):
        #    result[i] = 'è'
        # è before -ce (pièce)
        elif after.lower() == 'c' and after2.lower() == 'e':
            result[i] = 'è'
        # è: i?r pattern (première)
        elif before.lower() == 'i' and after.lower() == 'r':
            result[i] = 'è'
        # è: ?v (Genève: n?v → è)
        elif after.lower() == 'v':
            result[i] = 'è'
        # ê before final -t (arrêt, forêt) - in manual map
        elif after.lower() == 't' and (i+2 >= len(result) or result[i+2] in (' ', '', "'", ',', '.', ')')):
            result[i] = 'ê'
        # ô after h
        elif before.lower() == 'h':
            result[i] = 'ô'
        # Word-initial (i=0 in token): ? → mostly é
        elif i == 0:
            if after.lower() == 'l' and after2 and after2.lower() not in 'aeioué':
                result[i] = 'î'   # île
            elif after.lower() == 'g' and after2.lower() == 'e':
                result[i] = 'â'   # âge
            else:
                result[i] = 'é'
        # Word-final ? after vowel 'e' → likely real question mark
        elif not after and before.lower() in 'aeiouy':
            result[i] = '?'   # Keep as real ?
        # Default: é
        else:
            result[i] = 'é'
        i += 1
    return ''.join(result)

def correct_token(token, char="?", _map = MANUAL_MAP):
    if token in _map:
        return _map[token]
    return correct_by_rules(token, char=char)

def fix_cell(cell_value, char="?", _map=MANUAL_MAP):
    if not isinstance(cell_value, str) or char not in cell_value:
        return cell_value
    if char == "?":
        parts = re.split(r"([A-Za-z?àâäéèêëîïôùûüçœæ'-]+)", cell_value)
    elif char == "�":
        parts = re.split(r"([A-Za-z�àâäéèêëîïôùûüçœæ'-]+)", cell_value)
    result = []
    for part in parts:
        if char in part and re.search(r'[A-Za-z]', part):
            result.append(correct_token(part, char=char, _map=_map))
        elif part == char:
            result.append('à')   # standalone ? is always "à"
        else:
            result.append(part)
    return ''.join(result)

ID_COLS = {
    'alias', 'date_str', 'stt_filename', 'mp3_filenames', 'stripped_OID',
    'exact_date', 'broadcast_date', 'cls_ID', 'OID', 'login',
    'sequence', 'modified_by', 'modified_on', 'work_duration',
    'work_duration_compl', 'spt_filenames'
}

#### Try to repreat the approach with the character "�"

Claude's approach fixed the problems with the character "?" but another character is there.

However there are still quite a bit of problems with the fix. I found more examples which had erroneous corrections but much more probably exist.
What we did was the best we could.

In [48]:
SECOND_MANUAL_MAP = {k.replace("?", "�"): v for k,v in MANUAL_MAP.items()}
# add examples by hand from errors remaining spotted
SECOND_MANUAL_MAP["Ch�teaureynaud"] = "Châteaureynaud"
SECOND_MANUAL_MAP

{'�': 'à',
 'Parl�': 'Parlé',
 "'Parl�": "'Parlé",
 'Clarifi�': 'Clarifié',
 'Valid�': 'Validé',
 "Premi�re'": "Première'",
 'Accept�': 'Accepté',
 'Mont�': 'Monté',
 'Premi�re': 'Première',
 'St�r�o': 'Stéréo',
 "'Pr�sentateur": "'Présentateur",
 'Pr�sentateur': 'Présentateur',
 "'Interview�": "'Interviewé",
 'Interview�': 'Interviewé',
 'Gen�ve': 'Genève',
 "'Gen�ve": "'Genève",
 "Gen�ve'": "Genève'",
 'Radio-Gen�ve': 'Radio-Genève',
 "Radio-Gen�ve'": "Radio-Genève'",
 'Neuch�tel': 'Neuchâtel',
 "'Neuch�tel": "'Neuchâtel",
 "Neuch�tel'": "Neuchâtel'",
 'neuch�telois': 'neuchâtelois',
 'neuch�teloise': 'neuchâteloise',
 'B�le': 'Bâle',
 'Del�mont': 'Delémont',
 'Z�rich': 'Zürich',
 'Montr�al': 'Montréal',
 'J�rusalem': 'Jérusalem',
 "J�rusalem'": "Jérusalem'",
 'T�h�ran': 'Téhéran',
 'Qu�bec': 'Québec',
 'Alg�rie': 'Algérie',
 "'Alg�rie'": "'Algérie'",
 "d'Alg�rie": "d'Algérie",
 "l'Alg�rie": "l'Algérie",
 'P�kin': 'Pékin',
 'Cor�e': 'Corée',
 'Ha�ti': 'Haïti',
 'Za�re': 'Zaïre',
 'Is

In [51]:
df_to_fix_path = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata.rts_v3.csv"
df_fixed_path_int = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata_rts_fixed_int.csv"
df_fixed_path = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata_rts_fixed.csv"

df_to_fix = pd.read_csv(df_to_fix_path)

TEXT_COLS = [c for c in df_to_fix.columns if c not in ID_COLS]

print("Processing cells for char = '?' ...")
total_fixes = 0
for col in TEXT_COLS:
    before = df_to_fix[col].copy()
    df_to_fix[col] = df_to_fix[col].apply(fix_cell)
    fixes = (before != df_to_fix[col]).sum()
    total_fixes += fixes
    if fixes > 0:
        print(f"  {col}: {fixes} cells modified")

print(f"\nTotal cells modified: {total_fixes}")

# Verify key rows
print("\n--- Sample verification ---")
check_cols = ['broadcast_episode_title', 'content_summary', 'workflow_status', 'document_type', 'modulation_type']
for col in check_cols:
    samples = df_to_fix[col].dropna().head(5).tolist()
    print(f"\n{col}:")
    for s in samples[:3]:
        print(f"  {str(s)[:120]}")


print("\nSaving...")
df_to_fix.to_csv(df_fixed_path_int, index=False)


print("Processing cells for char = '�' ...")
total_fixes = 0
for col in TEXT_COLS:
    before = df_to_fix[col].copy()
    df_to_fix[col] = df_to_fix[col].apply(fix_cell, char='�', _map=SECOND_MANUAL_MAP)
    fixes = (before != df_to_fix[col]).sum()
    total_fixes += fixes
    if fixes > 0:
        print(f"  {col}: {fixes} cells modified")

print(f"\nTotal cells modified: {total_fixes}")

# Verify key rows
print("\n--- Sample verification ---")
check_cols = ['broadcast_episode_title', 'content_summary', 'workflow_status', 'document_type', 'modulation_type']
for col in check_cols:
    samples = df_to_fix[col].dropna().head(5).tolist()
    print(f"\n{col}:")
    for s in samples[:3]:
        print(f"  {str(s)[:120]}")

print("\nSaving...")
df_to_fix.to_csv(df_fixed_path, index=False)
print("Done!")

Processing cells for char = '?' ...
  broadcast_episode_title: 19134 cells modified
  broadcast_program_name: 1549 cells modified
  document_type: 20956 cells modified
  physical_support_history: 3576 cells modified
  production_type: 521 cells modified
  recording_place: 19605 cells modified
  rights_notes: 22818 cells modified
  rights_status: 22332 cells modified
  series_title: 8917 cells modified
  content_summary: 21474 cells modified
  workflow_status: 20956 cells modified
  assembly_status: 22585 cells modified
  live: 670 cells modified
  modulation_type: 4832 cells modified
  geographical_descriptors: 15692 cells modified
  person_descriptors: 16951 cells modified
  thematical_descriptors: 18174 cells modified
  rights_usage_possibilities: 8538 cells modified
  radio_channels: 15075 cells modified
  subdomains: 10830 cells modified
  recording_dates: 492 cells modified
  first_broadcast_dates: 1056 cells modified
  supports: 16948 cells modified
  participants: 17654 cells mo

## Perform some additional post-processing and cleaning 

This is specifically to separate the case for the metadata and issue index creation

In [ ]:
rts_metadata_filepath = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata_rts.csv"

rts_metadata_df = pd.read_csv(rts_metadata_filepath)
print(len(rts_metadata_df))
rts_metadata_df.head()

26261


,alias,date_str,stt_filename,mp3_filenames,stripped_OID,exact_date,broadcast_date,cls_ID,OID,login,...,person_descriptors,thematical_descriptors,rights_usage_possibilities,radio_channels,subdomains,recording_dates,first_broadcast_dates,supports,spt_filenames,participants
0,ana_media,16/12/1996,677E6735-8DEA-44F1-A52F-142BFEF9AB2E_STT.xml,['677e6735-8dea-44f1-a52f-142bfef9ab2e_7UBM_05...,677E6735-8DEA-44F1-A52F-142BFEF9AB2E,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{677E6735-8DEA-44F1-A52F-142BFEF9AB2E},NaN,...,"['X-Files', 'Aux frontières du réel']","['série télèvisée', 'science-fiction']",NaN,['Espace 2'],['Interview'],['~__/12/1996 - ~__/12/1996'],['16/12/1996 - 16/12/1996'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,"[None, '7UBM_057338_1{8cfcf300-a815-4f92-bea2-...","[{'name': 'Frias, Roxanne', 'function': 'Inter..."
1,ana_media,26/05/1997,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484_STT.xml,['640e3c0b-40f0-4bd9-83c6-1ff4bce16484_1BBM_05...,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{640E3C0B-40F0-4BD9-83C6-1FF4BCE16484},NaN,...,NaN,"['école primaire', 'Internet', 'technique péda...",NaN,['Espace 2'],"['Commentaire', 'Parlé divers']",['~__/05/1997 - ~__/05/1997'],['26/05/1997 - 26/05/1997'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,['1BBM_058066_6{2782ba11-7050-44d3-bef1-a81252...,"[{'name': 'Dubois, Laurent', 'function': 'Inte..."
2,ana_media,20/01/1997,2AF13E50-C6A2-49E5-9851-06C441833B50_STT.xml,['2af13e50-c6a2-49e5-9851-06c441833b50_RPBM_05...,2AF13E50-C6A2-49E5-9851-06C441833B50,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{2AF13E50-C6A2-49E5-9851-06C441833B50},NaN,...,"['SSR', 'TSR']","['censure', 'télévision', 'morale']",NaN,['Espace 2'],['Interview'],['~__/04/1997 - ~__/04/1997'],['20/01/1997 - 20/01/1997'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,"[None, 'RPBM_057474_1{8116d0d3-1c12-44cf-a8a2-...","[{'name': 'Duparc, Nicole', 'function': 'Inter..."
3,ana_media,11/11/1996,C940BD19-5503-4918-852B-D40C1C18B359_STT.xml,['c940bd19-5503-4918-852b-d40c1c18b359_O1BM_05...,C940BD19-5503-4918-852B-D40C1C18B359,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{C940BD19-5503-4918-852B-D40C1C18B359},NaN,...,NaN,"['série télèvisée', 'urgence médicale', 'télés...",NaN,['Espace 2'],['Interview'],['~__/11/1996 - ~__/11/1996'],['11/11/1996 - 11/11/1996'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,['O1BM_057153_2{396b576c-7ed9-4018-a251-c12a84...,"[{'name': 'Kiefer, B.', 'function': 'Interview..."
4,ana_media,21/04/1997,6EE0054C-042D-42E6-B11F-FEB6C0353B5A_STT.xml,['6ee0054c-042d-42e6-b11f-feb6c0353b5a_FHBM_05...,6EE0054C-042D-42E6-B11F-FEB6C0353B5A,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{6EE0054C-042D-42E6-B11F-FEB6C0353B5A},NaN,...,NaN,"['enseignement secondaire', 'technique pédagog...",NaN,['Espace 2'],['Interview'],['~__/04/1997 - ~__/04/1997'],['21/04/1997 - 21/04/1997'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,['FHBM_055791_2{e8455981-078d-44f2-bb94-2e22cd...,"[{'name': 'Prophan, Geneviève', 'function': 'I..."


#### Columns filtering 

There was originally 36856 documents in the metadata, 10659 of which were missing MP3 and/or XML files (26261 had both). 

First remove the unused columns in this context, as well as all broadcasts which have no dates.

There are two main uses: the metadata, and the issue index. The filtering for the issue index columns will take place later on

In [5]:
rts_metadata_df.columns

Index(['alias', 'date_str', 'stt_filename', 'mp3_filenames', 'stripped_OID',
       'exact_date', 'broadcast_date', 'cls_ID', 'OID', 'login',
       'broadcast_episode_title', 'sequence', 'broadcast_program_name',
       'document_type', 'hierarchy_level', 'modified_by', 'modified_on',
       'physical_support_history', 'production_type', 'recording_place',
       'rights_notes', 'rights_status', 'series_title', 'content_summary',
       'workflow_status', 'assembly_status', 'live', 'modulation_type',
       'work_duration', 'work_duration_compl', 'geographical_descriptors',
       'person_descriptors', 'thematical_descriptors',
       'rights_usage_possibilities', 'radio_channels', 'subdomains',
       'recording_dates', 'first_broadcast_dates', 'supports', 'spt_filenames',
       'participants'],
      dtype='str')

In [6]:
# remove all the broadcasts without a date as we cannot process them
valid_rts_df = rts_metadata_df[~rts_metadata_df['date_str'].isna()]
valid_rts_df = valid_rts_df[['alias', 'date_str', 'stt_filename', 'mp3_filenames', 'stripped_OID', 'OID', 'exact_date', 'broadcast_date', 
                             'broadcast_episode_title', 'broadcast_program_name',
                             'recording_place', 'series_title', 'content_summary', 'live', 
                             'work_duration', 'participants', 'radio_channels', 
                             'recording_dates', 'first_broadcast_dates']]
print(len(valid_rts_df))
valid_rts_df.head()

26225


,alias,date_str,stt_filename,mp3_filenames,stripped_OID,OID,exact_date,broadcast_date,broadcast_episode_title,broadcast_program_name,recording_place,series_title,content_summary,live,work_duration,participants,radio_channels,recording_dates,first_broadcast_dates
0,ana_media,16/12/1996,677E6735-8DEA-44F1-A52F-142BFEF9AB2E_STT.xml,['677e6735-8dea-44f1-a52f-142bfef9ab2e_7UBM_05...,677E6735-8DEA-44F1-A52F-142BFEF9AB2E,{677E6735-8DEA-44F1-A52F-142BFEF9AB2E},True,True,"""X-Files"" ou ""Aux frontières du réel""",Analyse des médias,NaN,NaN,"Présentation de la série-culte. Le succès, com...",Non live,00:00:00.000,"[{'name': 'Frias, Roxanne', 'function': 'Inter...",['Espace 2'],['~__/12/1996 - ~__/12/1996'],['16/12/1996 - 16/12/1996']
1,ana_media,26/05/1997,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484_STT.xml,['640e3c0b-40f0-4bd9-83c6-1ff4bce16484_1BBM_05...,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484,{640E3C0B-40F0-4BD9-83C6-1FF4BCE16484},True,True,Internet à l'Ecole primaire d'Avully (GE),Analyse des médias,Avully,NaN,NaN,Non live,00:00:00.000,"[{'name': 'Dubois, Laurent', 'function': 'Inte...",['Espace 2'],['~__/05/1997 - ~__/05/1997'],['26/05/1997 - 26/05/1997']
2,ana_media,20/01/1997,2AF13E50-C6A2-49E5-9851-06C441833B50_STT.xml,['2af13e50-c6a2-49e5-9851-06c441833b50_RPBM_05...,2AF13E50-C6A2-49E5-9851-06C441833B50,{2AF13E50-C6A2-49E5-9851-06C441833B50},True,True,Le carré blanc,Analyse des médias,Genève;Fribourg,NaN,NaN,Non live,00:00:00.000,"[{'name': 'Duparc, Nicole', 'function': 'Inter...",['Espace 2'],['~__/04/1997 - ~__/04/1997'],['20/01/1997 - 20/01/1997']
3,ana_media,11/11/1996,C940BD19-5503-4918-852B-D40C1C18B359_STT.xml,['c940bd19-5503-4918-852b-d40c1c18b359_O1BM_05...,C940BD19-5503-4918-852B-D40C1C18B359,{C940BD19-5503-4918-852B-D40C1C18B359},True,True,"Le feuilleton télévisé ""Urgences""",Analyse des médias,Genève,NaN,Analyse de la série et des raisons de son succès.,Non live,00:00:00.000,"[{'name': 'Kiefer, B.', 'function': 'Interview...",['Espace 2'],['~__/11/1996 - ~__/11/1996'],['11/11/1996 - 11/11/1996']
4,ana_media,21/04/1997,6EE0054C-042D-42E6-B11F-FEB6C0353B5A_STT.xml,['6ee0054c-042d-42e6-b11f-feb6c0353b5a_FHBM_05...,6EE0054C-042D-42E6-B11F-FEB6C0353B5A,{6EE0054C-042D-42E6-B11F-FEB6C0353B5A},True,True,Le journal à l'école,Analyse des médias,Genève;Fribourg,NaN,NaN,Non live,00:00:00.000,"[{'name': 'Prophan, Geneviève', 'function': 'I...",['Espace 2'],['~__/04/1997 - ~__/04/1997'],['21/04/1997 - 21/04/1997']


Finally we removed 36 broadcasts which were missing their date, ending up with 26225 radio issues

In [7]:
26261-26225

36

In [ ]:
"Valid�"

## index_file building (not final nor correct)

In [70]:
# Function to build issue index structure similar to issue_index.sub.json
def build_issue_index(documents, program_alias, program_dir):
    """
    Build an issue index structure from parsed documents.
    
    Structure:
    {
        "program_alias": {
            "year": {
                "month": [
                    {
                        "day": int,
                        "edition": str (a, b, c, etc.),
                        "local_path": str,
                        "audio_file": str or list,
                        ... other document metadata
                    },
                    ...
                ],
                ...
            },
            ...
        }
    }
    
    Args:
        documents: list of parsed document dictionaries
        program_alias: the program name/alias (e.g., "causerie_uni")
        program_dir: the path to the program directory
    
    Returns:
        tuple: (issue_index_dict, missing_audio_files_dict)
    """
    from datetime import datetime
    from collections import defaultdict
    
    issue_index = {program_alias: {}}
    missing_audio_files = {program_alias: []}
    
    # Group documents by recording date
    date_groups = defaultdict(list)
    
    for doc in documents:
        # Parse recording date (format: "DD/MM/YYYY - DD/MM/YYYY")
        recording_dates = doc.get('recordingdates', [])
        if not recording_dates:
            missing_audio_files[program_alias].append({
                'title': doc.get('TITLE'),
                'reason': 'No recording date'
            })
            continue
        
        date_str = recording_dates[0].split(' - ')[0]  # Get first date
        try:
            date_obj = datetime.strptime(date_str, "%d/%m/%Y")
            year = str(date_obj.year)
            month = f"{date_obj.month:02d}"
            day = date_obj.day
            date_key = (year, month, day)
            date_groups[date_key].append(doc)
        except:
            missing_audio_files[program_alias].append({
                'title': doc.get('TITLE'),
                'reason': f'Could not parse date: {date_str}'
            })
            continue
    
    # Build the nested structure
    for (year, month, day), docs_for_day in sorted(date_groups.items()):
        # Initialize year and month if not exist
        if year not in issue_index[program_alias]:
            issue_index[program_alias][year] = {}
        if month not in issue_index[program_alias][year]:
            issue_index[program_alias][year][month] = []
        
        # Assign editions (a, b, c, etc.) to documents on the same day
        for edition_idx, doc in enumerate(docs_for_day):
            edition = chr(ord('a') + edition_idx)  # 'a', 'b', 'c', ...
            
            # Extract audio files
            audio_files = []
            if doc.get('supports'):
                for support in doc['supports']:
                    filename = support.get('filename')
                    if filename:
                        audio_files.append(filename)
            
            # Create issue entry
            issue_entry = {
                'day': day,
                'edition': edition,
                'local_path': program_dir,
                'title': doc.get('TITLE'),
                'broadcast': doc.get('BROADCAST'),
                'summary': doc.get('SUMMARY'),
                'participants': doc.get('participants', []),
                'geographic_descriptors': doc.get('geographicaldescriptors', []),
                'thematic_descriptors': doc.get('thematicaldescriptors', []),
                'duration': doc.get('WORKDURATION'),
                'recording_dates': doc.get('recordingdates', [])
            }
            
            # Handle audio_file field (single value if 1 file, list if multiple)
            if not audio_files:
                # Missing audio files - add to separate tracking dict
                missing_audio_files[program_alias].append({
                    'title': doc.get('TITLE'),
                    'date': f"{day}/{month}/{year}",
                    'edition': edition,
                    'reason': 'No audio files in metadata'
                })
            elif len(audio_files) == 1:
                issue_entry['audio_file'] = audio_files[0]
            else:
                issue_entry['audio_file'] = audio_files
            
            issue_index[program_alias][year][month].append(issue_entry)
    
    return issue_index, missing_audio_files


# Test with the example documents
issue_index, missing_files = build_issue_index(all_documents, 'causerie_uni', '/mnt/project_impresso/original/RTS/causerie_uni')

print(f"Issue Index built successfully!")
print(f"Programs: {list(issue_index.keys())}")

for program, years_data in issue_index.items():
    print(f"\n{program}:")
    print(f"  Years: {sorted(years_data.keys())}")
    
    for year, months_data in sorted(years_data.items()):
        print(f"    {year}:")
        for month, issues in sorted(months_data.items()):
            print(f"      {month}: {len(issues)} issue(s)")
            for issue in issues[:2]:  # Show first 2
                audio_info = f"audio: {issue.get('audio_file', 'N/A')}"
                if isinstance(issue.get('audio_file'), list):
                    audio_info = f"audio: {len(issue['audio_file'])} files"
                print(f"        Day {issue['day']}-{issue['edition']}: {audio_info}")

print(f"\n\nMissing audio files:")
for program, missing in missing_files.items():
    print(f"{program}: {len(missing)} document(s) with missing audio")
    for m in missing[:3]:  # Show first 3
        print(f"  - {m.get('title', 'N/A')[:60]}... ({m.get('reason', 'N/A')})")


Issue Index built successfully!
Programs: ['causerie_uni']

causerie_uni:
  Years: ['1939', '1940', '1942']
    1939:
      11: 6 issue(s)
        Day 4-a: audio: 1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.wav
        Day 20-a: audio: 1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wav
    1940:
      11: 1 issue(s)
        Day 26-a: audio: 1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.wav
    1942:
      10: 1 issue(s)
        Day 3-a: audio: N/A


Missing audio files:
causerie_uni: 2 document(s) with missing audio
  - Le Tessin, facteur de coh?sion nationale : Causerie de Giova... (No audio files in metadata)
  - Epicure ou la religion du plaisir : Causerie de Ren? Schaere... (No audio files in metadata)


In [71]:
issue_index

{'causerie_uni': {'1939': {'11': [{'day': 4,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "L'enseignement de l'histoire. Causerie de Gonzague de Reynold",
     'broadcast': 'Causerie universitaire',
     'summary': "Cr?ation ? l'Universit? de Fribourg de la Chaire d'histoire de la civilisation moderne. L'enseignement de l'histoire a pour but d'initier les auditeurs ? la vie, de leur donner les connaissances et la compr?hension de l'Europe actuelle et tragique. L'?ducation de la pens?e doit d?velopper le sens critique en multipliant les termes de comparaison. La m?connaissance de l'histoire comme sympt?me de l'inculture d'une grande partie de la jeunesse. Devenir contemporain du pass? pour mieux le comprendre et appr?hender le pr?sent ? la lumi?re des origines.",
     'participants': [{'name': 'Reynold, Gonzague de',
       'function': 'Conf?rencier/e',
       'role': '?crivain'}],
     'geographic_descriptors': ['Fribourg (can