# NB: labels for content item types need to be consistent with the JSON schema
# https://impresso.github.io/impresso-schemas/json/newspaper/issue.schema.json
CONTENTITEM_TYPE_ARTICLE = "article"
CONTENTITEM_TYPE_ADVERTISEMENT = "ad"
CONTENTITEM_TYPE_OBITUARY = "death_notice"
CONTENTITEM_TYPE_TABLE = "table"
CONTENTITEM_TYPE_WEATHER = "weather"
CONTENTITEM_TYPE_IMAGE = "image"
CONTENTITEM_TYPE_CHAPTER = "chapter"
CONTENTITEM_TYPE_BULLETIN = "radio_bulletin"
CONTENTITEM_TYPE_BROADCAST = "radio_broadcast_episode"
CONTENTITEM_TYPE_CHRONICLE = "chronicle"
CONTENTITEM_TYPE_DISCUSSION = "discussion"
CONTENTITEM_TYPE_ENTERTAINMENT = "entertainment"

CONTENTITEM_TYPES = [
    CONTENTITEM_TYPE_ARTICLE,
    CONTENTITEM_TYPE_ADVERTISEMENT,
    CONTENTITEM_TYPE_IMAGE,
    CONTENTITEM_TYPE_OBITUARY,
    CONTENTITEM_TYPE_TABLE,
    CONTENTITEM_TYPE_WEATHER,
    CONTENTITEM_TYPE_CHAPTER,
    CONTENTITEM_TYPE_BULLETIN,
    CONTENTITEM_TYPE_BROADCAST,
    CONTENTITEM_TYPE_CHRONICLE,
    CONTENTITEM_TYPE_DISCUSSION,
    CONTENTITEM_TYPE_ENTERTAINMENT,
]
